const categorias = {
    pesquisar:      { nome: "pesquisar",        titulo: "Pesquisar uma palavra" },
    numeros:        { nome: "numeros",          titulo: "Números" },
    alfabeto:       { nome: "alfabeto",         titulo: "Letras do Alfabeto" },
    animais:        { nome: "animais",          titulo: "Animais" },
    frutas:         { nome: "frutas",           titulo: "Frutas" },
    cores:          { nome: "cores",            titulo: "Cores" },
    diasSemana:     { nome: "diasSemana",       titulo: "Dias da Semana" },
    meses:          { nome: "meses",            titulo: "Meses" },
    familia:        { nome: "familia",          titulo: "Família" },
    profissoes:     { nome: "profissoes",       titulo: "Profissões" },
    transportes:    { nome: "transportes",      titulo: "Transportes" },
    pontosCardeais: { nome: "pontosCardeais",   titulo: "Pontos Cardeais" },
    esportes:       { nome: "esportes",         titulo: "Esportes" },
    disciplinas:    { nome: "disciplinas",      titulo: "Disciplinas" },
    pronomes:       { nome: "pronomes",         titulo: "Pronomes" },
    verbosDirec:    { nome: "verbosDirec",      titulo: "Verbos Direcionais" },    
};