const dicionario = [
    { palavra: "A", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/1.jpg"},
    { palavra: "B", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/2.jpg"},
    { palavra: "C", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/3.jpg"},
    { palavra: "Ç", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/4.jpg"},
    { palavra: "D", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/5.jpg"},
    { palavra: "E", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/6.jpg"},
    { palavra: "F", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/7.jpg"},
    { palavra: "G", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/8.jpg"},
    { palavra: "H", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/9.jpg"},
    { palavra: "I", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/10.jpg"},
    { palavra: "J", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/11.jpg"},
    { palavra: "K", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/12.jpg"},
    { palavra: "L", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/13.jpg"},    
    { palavra: "M", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/14.jpg"},
    { palavra: "N", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/15.jpg"},
    { palavra: "O", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/16.jpg"},
    { palavra: "P", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/17.jpg"},
    { palavra: "Q", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/18.jpg"},
    { palavra: "R", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/19.jpg"},
    { palavra: "S", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/20.jpg"},
    { palavra: "T", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/21.jpg"},
    { palavra: "U", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/22.jpg"},
    { palavra: "V", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/23.jpg"},
    { palavra: "W", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/24.jpg"},
    { palavra: "X", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/25.jpg"},
    { palavra: "Y", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/26.jpg"},
    { palavra: "Z", categoria: categorias.alfabeto.nome, url: "imagens/alfabeto/27.jpg"},

    { palavra: "Abelha", categoria: categorias.animais.nome, url: "imagens/palavras/a/1.jpg"},
    { palavra: "Abraçar", url: "imagens/palavras/a/2.jpg"},
    { palavra: "Abusar", url: "imagens/palavras/a/4.jpg"},
    { palavra: "Abstrato  ", url: "imagens/palavras/a/5.jpg"},
    { palavra: "Acabar", url: "imagens/palavras/a/6.jpg"},
    { palavra: "Academia", categoria: categorias.esportes.nome, url: "imagens/palavras/a/7.jpg"},
    { palavra: "Aceitar", url: "imagens/palavras/a/8.jpg"},
    { palavra: "Acender", url: "imagens/palavras/a/9.jpg"},
    { palavra: "Acessibilidade", url: "imagens/palavras/a/10.jpg"},
    { palavra: "Achar", descricao: "Opinar, Pensar, Supor. (Ex: Acho que é importante.  Ela acha que eu sou bonita)", url: "imagens/palavras/a/11.jpg"},
    { palavra: "Achar", descricao: "Encontrar pessoas ou objetos. (Ex. Achei meu primo  no bar. Papai achou dinheiro na rua)", url: "imagens/palavras/a/12.jpg"},
    { palavra: "Aconselhar", url: "imagens/palavras/a/13.jpg"},
    { palavra: "Acontecer", descricao: "O que ocorreu. (Ex: O que aconteceu com você que não foi a aula?)", url: "imagens/palavras/a/14.jpg"},
    { palavra: "Acontecer", descricao: "O que ocorreu. (Ex: O que aconteceu com você que não foi a aula?)", url: "imagens/palavras/a/15.jpg"},
    { palavra: "Acordar ", url: "imagens/palavras/a/16.jpg"},
    { palavra: "Acostumar ", url: "imagens/palavras/a/17.jpg"},
    { palavra: "Açougue", url: "imagens/palavras/a/18.jpg"},
    { palavra: "Acreditar ", url: "imagens/palavras/a/19.jpg"},
    { palavra: "Acusar-me", url: "imagens/palavras/a/20.jpg"},
    { palavra: "Acusar-te", url: "imagens/palavras/a/21.jpg"},
    { palavra: "Admirar", url: "imagens/palavras/a/22.jpg"},
    { palavra: "Advogad@", categoria: categorias.profissoes.nome, url: "imagens/palavras/a/23.jpg"},
    { palavra: "Aeroporto", categoria: categorias.transportes.nome, url: "imagens/palavras/a/24.jpg"},
    { palavra: "Agora", url: "imagens/palavras/a/25.jpg"},
    { palavra: "Águia / Gavião",  categoria: categorias.animais.nome, url: "imagens/palavras/a/27.jpg"},
    { palavra: "AIDS ", url: "imagens/palavras/a/28.jpg"},
    { palavra: "Ainda não ", url: "imagens/palavras/a/29.jpg"},
    { palavra: "Ajudar-me", url: "imagens/palavras/a/30.jpg"},
    { palavra: "Ajudar-te", url: "imagens/palavras/a/30-2.jpg"},
    { palavra: "Algo", url: "imagens/palavras/a/31.jpg"},
    { palavra: "Alguém", url: "imagens/palavras/a/32.jpg"},
    { palavra: "Alguma ", url: "imagens/palavras/a/33.jpg"},
    { palavra: "Alimentação", url: "imagens/palavras/a/34.jpg"},
    { palavra: "Alongamento", categoria: categorias.esportes.nome, url: "imagens/palavras/a/35.jpg"},
    { palavra: "Altas Habilidades", url: "imagens/palavras/a/36.jpg"},
    { palavra: "Alt@", url: "imagens/palavras/a/37.jpg"},
    { palavra: "Altura", url: "imagens/palavras/a/38.jpg"},
    { palavra: "Alugar", url: "imagens/palavras/a/39.jpg"},
    { palavra: "Amanhã", url: "imagens/palavras/a/40.jpg"},
    { palavra: "Amante", url: "imagens/palavras/a/41.jpg"},    
    { palavra: "Amarelo ", categoria: categorias.cores.nome, url: "imagens/palavras/a/42.jpg"},
    { palavra: "Amor", url: "imagens/palavras/a/43.jpg"},
    { palavra: "Amig@", url: "imagens/palavras/a/44.jpg"},
    { palavra: "Amizade", url: "imagens/palavras/a/45.jpg"},
    { palavra: "Ângulo", url: "imagens/palavras/a/46.jpg"},
    { palavra: "Aniversário", url: "imagens/palavras/a/47.jpg"},
    { palavra: "Ano", url: "imagens/palavras/a/48.jpg"},
    { palavra: "Antes", url: "imagens/palavras/a/49.jpg"},
    { palavra: "Aonde", url: "imagens/palavras/a/50.jpg"},
    { palavra: "Apagar", url: "imagens/palavras/a/51.jpg"},
    { palavra: "Apontador ", url: "imagens/palavras/a/52.jpg"},
    { palavra: "Aposentadoria", url: "imagens/palavras/a/53.jpg"},
    { palavra: "Aposentar", url: "imagens/palavras/a/54.jpg"},
    { palavra: "Aprender", url: "imagens/palavras/a/55.jpg"},
    { palavra: "Aprovar", url: "imagens/palavras/a/56.jpg"},
    { palavra: "Aproveitar", url: "imagens/palavras/a/57.jpg"},
    { palavra: "Aranha", categoria: categorias.animais.nome, url: "imagens/palavras/a/58.jpg"},
    { palavra: "Arte", url: "imagens/palavras/a/59.jpg"},
    { palavra: "Assembléia Legislativa", url: "imagens/palavras/a/60.jpg"},    
    { palavra: "Assinar / Assinatura", url: "imagens/palavras/a/61.jpg"},
    { palavra: "Assistência Social", categoria: categorias.profissoes.nome, url: "imagens/palavras/a/62.jpg"},
    { palavra: "Associad@", url: "imagens/palavras/a/63.jpg"},
    { palavra: "Até", url: "imagens/palavras/a/64.jpg"},
    { palavra: "Atenção", descricao: "Atenção (Ex: Você preste atenção quando eu falar)", url: "imagens/palavras/a/65.jpg"},
    { palavra: "Atenção", descricao: "Atenção (Ex: Vocês prestem atenção, eu vou falar)", url: "imagens/palavras/a/66.jpg"},
    { palavra: "Atenção", descricao: "Atenção (Ex: Vocês prestem atenção ao que ele vai falar)", url: "imagens/palavras/a/67.jpg"},
    { palavra: "Atendimento", url: "imagens/palavras/a/68.jpg"},
    { palavra: "Atestado", url: "imagens/palavras/a/69.jpg"},
    { palavra: "Atletismo", categoria: categorias.esportes.nome, url: "imagens/palavras/a/70.jpg"},
    { palavra: "Atrás", url: "imagens/palavras/a/71.jpg"},
    { palavra: "Atrasar ", url: "imagens/palavras/a/72.jpg"},
    { palavra: "Aumentativo ", url: "imagens/palavras/a/73.jpg"},
    { palavra: "Avestruz ", categoria: categorias.animais.nome,  url: "imagens/palavras/a/74.jpg"},
    { palavra: "Avisar-me", url: "imagens/palavras/a/75.jpg"},
    { palavra: "Avisar-te ", url: "imagens/palavras/a/76.jpg"},
    { palavra: "Azar", url: "imagens/palavras/a/77.jpg"},
    { palavra: "Azul", categoria: categorias.cores.nome, url: "imagens/palavras/a/78.jpg"},
    
    { palavra: "Bactéria", url: "imagens/palavras/b/1.jpg"},
    { palavra: "Bagunçar", url: "imagens/palavras/b/2.jpg"},
    { palavra: "Bairro", url: "imagens/palavras/b/3.jpg"},
    { palavra: "Baix@", url: "imagens/palavras/b/4.jpg"},
    { palavra: "Bala", url: "imagens/palavras/b/5.jpg"},
    { palavra: "Balanço", url: "imagens/palavras/b/6.jpg"},
    { palavra: "Baleia", categoria: categorias.animais.nome, url: "imagens/palavras/b/7.jpg"},
    { palavra: "Banana", categoria: categorias.frutas.nome, url: "imagens/palavras/b/8.jpg"},
    { palavra: "Banco", url: "imagens/palavras/b/9.jpg"},
    { palavra: "Bandeira", url: "imagens/palavras/b/10.jpg"},
    { palavra: "Banheiro", url: "imagens/palavras/b/11.jpg"},
    { palavra: "Banho", url: "imagens/palavras/b/12.jpg"},
    { palavra: "Barato", url: "imagens/palavras/b/13.jpg"},
    { palavra: "Barco", categoria: categorias.transportes.nome, url: "imagens/palavras/b/14.jpg"},
    { palavra: "Barraca", url: "imagens/palavras/b/15.jpg"},
    { palavra: "Barulho", url: "imagens/palavras/b/16.jpg"},
    { palavra: "Basquete", categoria: categorias.esportes.nome, url: "imagens/palavras/b/17.jpg"},
    { palavra: "Bater", url: "imagens/palavras/b/18.jpg"},
    { palavra: "Batizado", url: "imagens/palavras/b/19.jpg"},
    { palavra: "Bebê", url: "imagens/palavras/b/20.jpg"},
    { palavra: "Beija-flor", categoria: categorias.animais.nome, url: "imagens/palavras/b/21.jpg"},
    { palavra: "Beijar", descricao: "Beijo romântico. (Ex.: Um casal de namorados beijava-se ardentemente no cinema)", url: "imagens/palavras/b/22.jpg"},
    { palavra: "Beijar", descricao: "Beijar no rosto. (Ex: A menina beijou seu amigo no rosto)", url: "imagens/palavras/b/23.jpg"},
    { palavra: "Beisebol", categoria: categorias.esportes.nome, url: "imagens/palavras/b/24.jpg"},
    { palavra: "Beleza", url: "imagens/palavras/b/25.jpg"},
    { palavra: "Bem-vindo", url: "imagens/palavras/b/26.jpg"},
    { palavra: "Bergamota", categoria: categorias.frutas.nome, url: "imagens/palavras/b/27.jpg"},
    { palavra: "Biblioteca", url: "imagens/palavras/b/28.jpg"},
    { palavra: "Biologia", categoria: categorias.disciplinas.nome, url: "imagens/palavras/b/29.jpg"},
    { palavra: "Bloqueado", url: "imagens/palavras/b/30.jpg"},
    { palavra: "Bo@", url: "imagens/palavras/b/31.jpg"},
    { palavra: "Boa noite", url: "imagens/palavras/b/32.jpg"},
    { palavra: "Boa tarde", url: "imagens/palavras/b/33.jpg"},
    { palavra: "Bobagem", url: "imagens/palavras/b/34.jpg"},
    { palavra: "Boca", url: "imagens/palavras/b/35.jpg"},
    { palavra: "Bode", categoria: categorias.animais.nome, url: "imagens/palavras/b/36.jpg"},
    { palavra: "Bola", url: "imagens/palavras/b/37.jpg"},
    { palavra: "Bom dia", url: "imagens/palavras/b/38.jpg"},
    { palavra: "Bombeiro", categoria: categorias.profissoes.nome, url: "imagens/palavras/b/39.jpg"},
    { palavra: "Borboleta", categoria: categorias.animais.nome, url: "imagens/palavras/b/40.jpg"},
    { palavra: "Borracha", url: "imagens/palavras/b/41.jpg"},    
    { palavra: "Boxe", categoria: categorias.esportes.nome, url: "imagens/palavras/b/42.jpg"},
    { palavra: "Brab@", url: "imagens/palavras/b/43.jpg"},
    { palavra: "Braço", url: "imagens/palavras/b/44.jpg"},
    { palavra: "Braille", url: "imagens/palavras/b/45.jpg"},
    { palavra: "Branco", categoria: categorias.cores.nome, url: "imagens/palavras/b/46.jpg"},
    { palavra: "Brigar", descricao: "Violência corporal. (Ex. Os meninos brigaram na s aída da escola)", url: "imagens/palavras/b/47.jpg"},
    { palavra: "Brigar", descricao: "Discussão (Ex. O cliente discutiu com o caixa da loja)", url: "imagens/palavras/b/48.jpg"},
    { palavra: "Burro", categoria: categorias.animais.nome, url: "imagens/palavras/b/49.jpg"}, 

    { palavra: "Cachorro / Cão",  categoria: categorias.animais.nome, url: "imagens/palavras/c/1.jpg"},
    { palavra: "Cadeia", url: "imagens/palavras/c/2.jpg"},
    { palavra: "Caderno", url: "imagens/palavras/c/3.jpg"},
    { palavra: "Caju", categoria: categorias.frutas.nome, url: "imagens/palavras/c/4.jpg"},
    { palavra: "Calendário", url: "imagens/palavras/c/5.jpg"},
    { palavra: "Câmara", url: "imagens/palavras/c/6.jpg"},
    { palavra: "Camarão", categoria: categorias.animais.nome, url: "imagens/palavras/c/7.jpg"},
    { palavra: "Camelo", categoria: categorias.animais.nome, url: "imagens/palavras/c/8.jpg"},
    { palavra: "Caminhar", url: "imagens/palavras/c/9.jpg"},
    { palavra: "Campainha", url: "imagens/palavras/c/10.jpg"},
    { palavra: "Camping", url: "imagens/palavras/c/11.jpg"},
    { palavra: "Canguru", categoria: categorias.animais.nome, url: "imagens/palavras/c/12.jpg"},  
    { palavra: "Cansar", url: "imagens/palavras/c/13.jpg"},
    { palavra: "Capacitação", url: "imagens/palavras/c/14.jpg"},
    { palavra: "Caracol", categoria: categorias.animais.nome, url: "imagens/palavras/c/15.jpg"},
    { palavra: "Caranguejo", categoria: categorias.animais.nome, url: "imagens/palavras/c/16.jpg"},
    { palavra: "Carne", url: "imagens/palavras/c/17.jpg"},
    { palavra: "Carneiro", categoria: categorias.animais.nome, url: "imagens/palavras/c/18.jpg"},
    { palavra: "Carta", url: "imagens/palavras/c/19.jpg"},
    { palavra: "Cartão", descricao: "Qualquer cartão magnético. (Ex: Cartão de banco, de supermercado)", url: "imagens/palavras/c/20.jpg"},
    { palavra: "Cartão", descricao: "Qualquer cartão magnético. (Ex: Cartão de banco, de supermercado)", url: "imagens/palavras/c/21.jpg"},
    { palavra: "Cartaz", url: "imagens/palavras/c/22.jpg"},
    { palavra: "Carteira de identidade", url: "imagens/palavras/c/23.jpg"},
    { palavra: "Carteira de trabalho", url: "imagens/palavras/c/24.jpg"},
    { palavra: "Casa", url: "imagens/palavras/c/25.jpg"},
    { palavra: "Casar", url: "imagens/palavras/c/26.jpg"},
    { palavra: "Castigar", url: "imagens/palavras/c/27.jpg"},
    { palavra: "Cavalo", categoria: categorias.animais.nome, url: "imagens/palavras/c/28.jpg"},
    { palavra: "Ceg@", url: "imagens/palavras/c/29.jpg"},
    { palavra: "Cemitério", url: "imagens/palavras/c/30.jpg"},
    { palavra: "Centavo", url: "imagens/palavras/c/31.jpg"},
    { palavra: "Cert@", url: "imagens/palavras/c/32.jpg"},
    { palavra: "Chamada", url: "imagens/palavras/c/33.jpg"},
    { palavra: "Chefe", categoria: categorias.profissoes.nome, url: "imagens/palavras/c/34.jpg"},
    { palavra: "Cheio", url: "imagens/palavras/c/35.jpg"},
    { palavra: "Cheiro", url: "imagens/palavras/c/36.jpg"},
    { palavra: "Cheque", url: "imagens/palavras/c/37.jpg"},
    { palavra: "Chorar", url: "imagens/palavras/c/38.jpg"},
    { palavra: "Chuva", url: "imagens/palavras/c/39.jpg"},
    { palavra: "Cicatriz", url: "imagens/palavras/c/40.jpg"},
    { palavra: "Cidadania", url: "imagens/palavras/c/41.jpg"},    
    { palavra: "Cidade", url: "imagens/palavras/c/42.jpg"},
    { palavra: "Ciência", url: "imagens/palavras/c/43.jpg"},
    { palavra: "Cigarra",  categoria: categorias.animais.nome, url: "imagens/palavras/c/44.jpg"},
    { palavra: "Cinema", url: "imagens/palavras/c/45.jpg"},
    { palavra: "Cinza", categoria: categorias.cores.nome, url: "imagens/palavras/c/46.jpg"},
    { palavra: "Claro", url: "imagens/palavras/c/47.jpg"},
    { palavra: "Clínica", url: "imagens/palavras/c/48.jpg"},
    { palavra: "Coala", categoria: categorias.animais.nome, url: "imagens/palavras/c/49.jpg"},
    { palavra: "Cobra", categoria: categorias.animais.nome, url: "imagens/palavras/c/50.jpg"},
    { palavra: "Coelho", categoria: categorias.animais.nome, url: "imagens/palavras/c/51.jpg"},
    { palavra: "Colar", url: "imagens/palavras/c/52.jpg"},
    { palavra: "Coitad@", url: "imagens/palavras/c/53.jpg"},
    { palavra: "Coisa", url: "imagens/palavras/c/54.jpg"},
    { palavra: "Colchão", url: "imagens/palavras/c/55.jpg"},
    { palavra: "Colega", url: "imagens/palavras/c/56.jpg"},
    { palavra: "Coletivo", url: "imagens/palavras/c/57.jpg"},
    { palavra: "Combinar", descricao: "Fazer um acordo. Planejar conjuntamente (Ex: Combi nei o encontro hoje à tarde. A festa ficou combinad a para sábado)", url: "imagens/palavras/c/58.jpg"},
    { palavra: "Combinar", descricao: "Harmonizar. (Ex: Quando vou vestir uma roupa, gosto de combinar as cores)", url: "imagens/palavras/c/59.jpg"},
    { palavra: "Começar", url: "imagens/palavras/c/60.jpg"},
    { palavra: "Como", url: "imagens/palavras/c/61.jpg"},
    { palavra: "Completo", url: "imagens/palavras/c/62.jpg"},
    { palavra: "Complicar", url: "imagens/palavras/c/63.jpg"},
    { palavra: "Comportamento", url: "imagens/palavras/c/64.jpg"},
    { palavra: "Comprar", url: "imagens/palavras/c/65.jpg"},
    { palavra: "Comprido", url: "imagens/palavras/c/66.jpg"},
    { palavra: "Computador", url: "imagens/palavras/c/67.jpg"},
    { palavra: "Comunicar", descricao: "Tratar. Entender-se. (Ex: Mesmo estando afastados, comunicavam-se frequentemente)", url: "imagens/palavras/c/68.jpg"},
    { palavra: "Comunicar", descricao: "Comunicação truncada. (Ex. A pessoa ouvinte tem di ficuldade de comunicar-se com o surdo se não sabe a  língua de sinais)", url: "imagens/palavras/c/69.jpg"},
    { palavra: "Concluir", descricao: "Pronto. (Ex. Você concluiu o trabalho)", url: "imagens/palavras/c/70.jpg"},
    { palavra: "Concluir", descricao: "Finalizado (Ex. Acabou a aula)", url: "imagens/palavras/c/71.jpg"},
    { palavra: "Concreto", url: "imagens/palavras/c/72.jpg"},
    { palavra: "Confirmar", descricao: "Equivalente a certo. (Ex. A resposta está certa)", url: "imagens/palavras/c/73.jpg"},
    { palavra: "Confirmar", descricao: "Afirmar. (Ex.: está confirmado o dia do casament o)", url: "imagens/palavras/c/74.jpg"},
    { palavra: "Congresso", url: "imagens/palavras/c/75.jpg"},
    { palavra: "Conhecer", url: "imagens/palavras/c/76.jpg"},
    { palavra: "Conseguir", url: "imagens/palavras/c/77.jpg"},
    { palavra: "Consertar", url: "imagens/palavras/c/78.jpg"},  
    { palavra: "Construir", url: "imagens/palavras/c/79.jpg"},
    { palavra: "Consultar", descricao: "Procurar o médico (Ex. você tem uma consulta hoje  às 14h)", url: "imagens/palavras/c/80.jpg"},
    { palavra: "Consultar", descricao: "Pesquisar (Ex. Você fez a consulta na internet)", url: "imagens/palavras/c/81.jpg"},
    { palavra: "Contabilidade", categoria: categorias.profissoes.nome, url: "imagens/palavras/c/82.jpg"},
    { palavra: "Contente", url: "imagens/palavras/c/83.jpg"},
    { palavra: "Conteúdo", url: "imagens/palavras/c/84.jpg"},
    { palavra: "Continuar", url: "imagens/palavras/c/84-2.jpg"},
    { palavra: "Contrato", url: "imagens/palavras/c/85.jpg"},
    { palavra: "Conversar", url: "imagens/palavras/c/86.jpg"},
    { palavra: "Cópia", url: "imagens/palavras/c/87.jpg"},
    { palavra: "Cor", url: "imagens/palavras/c/88.jpg"},
    { palavra: "Coragem", url: "imagens/palavras/c/89.jpg"},     
    { palavra: "Corpo", url: "imagens/palavras/c/90.jpg"},
    { palavra: "Correio", url: "imagens/palavras/c/91.jpg"},
    { palavra: "Correr", categoria: categorias.esportes.nome, url: "imagens/palavras/c/92.jpg"},
    { palavra: "Coruja",  categoria: categorias.animais.nome, url: "imagens/palavras/c/93.jpg"},
    { palavra: "Costas", url: "imagens/palavras/c/94.jpg"},
    { palavra: "Criança", url: "imagens/palavras/c/95.jpg"},
    { palavra: "Cuidar", url: "imagens/palavras/c/96.jpg"},
    { palavra: "Culpar", url: "imagens/palavras/c/97.jpg"},
    { palavra: "Culto", url: "imagens/palavras/c/98.jpg"},
    { palavra: "Cunhad@", categoria: categorias.familia.nome, url: "imagens/palavras/c/99.jpg"},
    { palavra: "Currículo", url: "imagens/palavras/c/100.jpg"},
    { palavra: "Curso", url: "imagens/palavras/c/101.jpg"},
    
    { palavra: "Dinheiro", url: "imagens/palavras/d/1.jpg"},
    { palavra: "De novo", url: "imagens/palavras/d/2.jpg"},
    { palavra: "Decidir", url: "imagens/palavras/d/3.jpg"},
    { palavra: "Dedo", url: "imagens/palavras/d/4.jpg"},
    { palavra: "Defeito", url: "imagens/palavras/d/5.jpg"},
    { palavra: "Defesa", descricao: "Tomar cuidado (Ex.: Você precisa tomar cuidado ao  sair à noite)", url: "imagens/palavras/d/6.jpg"},
    { palavra: "Defesa", descricao: "Resistir à agressão (Ex.: Você precisa aprender a se defender sozinho)", url: "imagens/palavras/d/7.jpg"},
    { palavra: "Deixar", url: "imagens/palavras/d/8.jpg"},
    { palavra: "Delícia", url: "imagens/palavras/d/9.jpg"},
    { palavra: "Demitir", descricao: "Despedir (Ex: Demiti o funcionário por justa causa)", url: "imagens/palavras/d/10.jpg"},
    { palavra: "Demitir", descricao: "Pedir demissão (Ex: Eu pedi demissão  porque esta va ganhando muito pouco)", url: "imagens/palavras/d/11.jpg"},
    { palavra: "Demitir", descricao: "Demitido (Ex: Eu fui demitido)", url: "imagens/palavras/d/12.jpg"},
    { palavra: "Dente", url: "imagens/palavras/d/13.jpg"},
    { palavra: "Demorar", url: "imagens/palavras/d/14.jpg"},
    { palavra: "Dentista", categoria: categorias.profissoes.nome, url: "imagens/palavras/d/15.jpg"},
    { palavra: "Dentro", url: "imagens/palavras/d/16.jpg"},
    { palavra: "Depende", url: "imagens/palavras/d/17.jpg"},
    { palavra: "Depois", url: "imagens/palavras/d/18.jpg"},
    { palavra: "Deputad@", categoria: categorias.profissoes.nome, url: "imagens/palavras/d/19.jpg"},
    { palavra: "Desconfiar / Duvidar", url: "imagens/palavras/d/20.jpg"},
    { palavra: "Desafio", url: "imagens/palavras/d/21.jpg"},
    { palavra: "Desculpar", url: "imagens/palavras/d/22.jpg"},
    { palavra: "Desempregad@", categoria: categorias.profissoes.nome, url: "imagens/palavras/d/23.jpg"},
    { palavra: "Desenhar", url: "imagens/palavras/d/24.jpg"},
    { palavra: "Desenvolver", url: "imagens/palavras/d/25.jpg"},
    { palavra: "Desmaiar", url: "imagens/palavras/d/26.jpg"},
    { palavra: "Desprezar", url: "imagens/palavras/d/27.jpg"},
    { palavra: "Devagar", url: "imagens/palavras/d/28.jpg"},
    { palavra: "Dever", descricao: "Dívida (Ex: Você me deve um churrasco)", url: "imagens/palavras/d/28-2.jpg"},
    { palavra: "Dever", descricao: "Obrigação (Ex: Você deve obedecer seus pais)", url: "imagens/palavras/d/29.jpg"},
    { palavra: "Dia", url: "imagens/palavras/d/31.jpg"},
    { palavra: "Diálogo", url: "imagens/palavras/d/32.jpg"},
    { palavra: "Dicionário", url: "imagens/palavras/d/33.jpg"},
    { palavra: "Didática", url: "imagens/palavras/d/34.jpg"},
    { palavra: "Direito", url: "imagens/palavras/d/35.jpg"},
    { palavra: "Diferente", url: "imagens/palavras/d/36.jpg"},
    { palavra: "Difícil", url: "imagens/palavras/d/37.jpg"},
    { palavra: "Diretor@", categoria: categorias.profissoes.nome, url: "imagens/palavras/d/38.jpg"},
    { palavra: "Diminutivo", url: "imagens/palavras/d/39.jpg"},
    { palavra: "Direto", url: "imagens/palavras/d/40.jpg"},
    { palavra: "Disciplina", url: "imagens/palavras/d/41.jpg"},
    { palavra: "Diretoria", url: "imagens/palavras/d/42.jpg"},
    { palavra: "Discutir", url: "imagens/palavras/d/43.jpg"},
    { palavra: "Disfarçar", url: "imagens/palavras/d/44.jpg"},
    { palavra: "Distância", url: "imagens/palavras/d/45.jpg"},
    { palavra: "Ditado", url: "imagens/palavras/d/46.jpg"},
    { palavra: "Divertida", url: "imagens/palavras/d/47.jpg"},
    { palavra: "Divórcio", url: "imagens/palavras/d/48.jpg"},
    { palavra: "Doce", url: "imagens/palavras/d/49.jpg"},
    { palavra: "Doação", url: "imagens/palavras/d/50.jpg"},
    { palavra: "Documento", url: "imagens/palavras/d/51.jpg"},
    { palavra: "Doença", url: "imagens/palavras/d/52.jpg"},
    { palavra: "Dor", url: "imagens/palavras/d/54.jpg"},
    { palavra: "Dor de cabeça", url: "imagens/palavras/d/55.jpg"},
    { palavra: "Dormir", url: "imagens/palavras/d/56.jpg"},
    { palavra: "Droga", url: "imagens/palavras/d/57.jpg"},
    { palavra: "Durex", url: "imagens/palavras/d/58.jpg"},
    { palavra: "Duro", url: "imagens/palavras/d/59.jpg"},
    { palavra: "Dúvida", url: "imagens/palavras/d/60.jpg"},    

    { palavra: "Economizar", url: "imagens/palavras/e/1.jpg"},
    { palavra: "Educação Física", categoria: categorias.disciplinas.nome, url: "imagens/palavras/e/2.jpg"},
    { palavra: "Educação / Ensinar", categoria: categorias.profissoes.nome, url: "imagens/palavras/e/3.jpg"},
    { palavra: "Educar", url: "imagens/palavras/e/4.jpg"},
    { palavra: "Egoísta", url: "imagens/palavras/e/5.jpg"},
    { palavra: "El@", descricao: "Uma pessoa (Ex: Ela comprou um tênis)", url: "imagens/palavras/e/6.jpg"},
    { palavra: "El@", descricao: "Duas pessoas (Ex. As duas foram para o cinema)", url: "imagens/palavras/e/7.jpg"},
    { palavra: "El@", descricao: "Três pessoas (Ex. As três amigas estavam conversa ndo no bar)", url: "imagens/palavras/e/8.jpg"},
    { palavra: "El@", descricao: "Quatro pessoas (Ex. Elas estavam andando na beira  da praia)", url: "imagens/palavras/e/9.jpg"},
    { palavra: "Eleição", url: "imagens/palavras/e/10.jpg"},
    { palavra: "Eletricidade", url: "imagens/palavras/e/11.jpg"},
    { palavra: "Emagrecer", url: "imagens/palavras/e/12.jpg"},
    { palavra: "E-mail", url: "imagens/palavras/e/13.jpg"},
    { palavra: "Empate", url: "imagens/palavras/e/14.jpg"},
    { palavra: "Empregad@", categoria: categorias.profissoes.nome, url: "imagens/palavras/e/15.jpg"},
    { palavra: "Emprego", url: "imagens/palavras/e/16.jpg"},
    { palavra: "Emprestar-me", url: "imagens/palavras/e/17.jpg"},
    { palavra: "Emprestar-te", url: "imagens/palavras/e/18.jpg"},
    { palavra: "Empurrar", url: "imagens/palavras/e/19.jpg"},
    { palavra: "Encontrar", url: "imagens/palavras/e/20.jpg"},
    { palavra: "Enfermeir@", categoria: categorias.profissoes.nome, url: "imagens/palavras/e/21.jpg"},
    { palavra: "Enganar", url: "imagens/palavras/e/22.jpg"},
    { palavra: "Enjoar", descricao: "Repugnar (Ex. Estou me sentindo enjoada)", url: "imagens/palavras/e/23.jpg"},
    { palavra: "Enjoar", descricao: "Entediar (Ex. Estou entediada com está festa)", url: "imagens/palavras/e/24.jpg"},
    { palavra: "Entender", url: "imagens/palavras/e/25.jpg"},
    { palavra: "Entender-não", url: "imagens/palavras/e/26.jpg"},
    { palavra: "Entre", url: "imagens/palavras/e/27.jpg"},
    { palavra: "Entregar", url: "imagens/palavras/e/28.jpg"},
    { palavra: "Entrevista", url: "imagens/palavras/e/29.jpg"},
    { palavra: "Enviar", url: "imagens/palavras/e/30.jpg"},
    { palavra: "Equipe", url: "imagens/palavras/e/31.jpg"},
    { palavra: "Errar", url: "imagens/palavras/e/32.jpg"},
    { palavra: "Escola", url: "imagens/palavras/e/33.jpg"},
    { palavra: "Escolher", url: "imagens/palavras/e/34.jpg"},
    { palavra: "Esconder", url: "imagens/palavras/e/35.jpg"},
    { palavra: "Escorpião", categoria: categorias.animais.nome, url: "imagens/palavras/e/36.jpg"},
    { palavra: "Escovar", descricao: "Dente (Ex.  Estou escovando os dentes)", url: "imagens/palavras/e/37.jpg"},
    { palavra: "Escovar", descricao: "Cabelo (Ex. Você precisa escovar os cabelos)", url: "imagens/palavras/e/38.jpg"},
    { palavra: "Escrav@", descricao: "Trabalho escravo (Ex. Trabalhei ontem como um esc ravo)", url: "imagens/palavras/e/39.jpg"},
    { palavra: "Escrav@", descricao: "Condição de escravo. (Ex. Os escravos sofriam nas mãos dos feitores)", url: "imagens/palavras/e/40.jpg"},
    { palavra: "Escrever", url: "imagens/palavras/e/41.jpg"},
    { palavra: "Escuro", url: "imagens/palavras/e/42.jpg"},
    { palavra: "Esgrima", categoria: categorias.esportes.nome, url: "imagens/palavras/e/43.jpg"},
    { palavra: "Espaço", url: "imagens/palavras/e/44.jpg"},
    { palavra: "Espanhol", url: "imagens/palavras/e/45.jpg"},
    { palavra: "Especial", url: "imagens/palavras/e/46.jpg"},
    { palavra: "Esperança", url: "imagens/palavras/e/47.jpg"},
    { palavra: "Esperar", descricao: "Aguardar. (Ex: Espere por mim)", url: "imagens/palavras/e/48.jpg"},
    { palavra: "Esperar", descricao: "Esperar rapidinho. (Ex: Espera um pouco que  volto logo)", url: "imagens/palavras/e/49.jpg"},
    { palavra: "Espiar", url: "imagens/palavras/e/50.jpg"},
    { palavra: "Esporte", categoria: categorias.esportes.nome, url: "imagens/palavras/e/51.jpg"},
    { palavra: "Esquecer", url: "imagens/palavras/e/52.jpg"},
    { palavra: "Esquerda", url: "imagens/palavras/e/53.jpg"},
    { palavra: "Esquilo", categoria: categorias.animais.nome, url: "imagens/palavras/e/54.jpg"},
    { palavra: "Est@", url: "imagens/palavras/e/55.jpg"},
    { palavra: "Estacionamento", url: "imagens/palavras/e/56.jpg"},
    { palavra: "Esquisit@", url: "imagens/palavras/e/57.jpg"},
    { palavra: "Estádio", categoria: categorias.esportes.nome, url: "imagens/palavras/e/58.jpg"},
    { palavra: "Estado", url: "imagens/palavras/e/59.jpg"},
    { palavra: "Estatuto", url: "imagens/palavras/e/60.jpg"},
    { palavra: "Estrutura", descricao: "Estrutura Língua Portuguesa. (Ex. A estrutura da f rase está errada)", url: "imagens/palavras/e/61.jpg"},
    { palavra: "Estrada", url: "imagens/palavras/e/62.jpg"},
    { palavra: "Estragar", url: "imagens/palavras/e/63.jpg"},
    { palavra: "Estranho", url: "imagens/palavras/e/64.jpg"},
    { palavra: "Estrutura", descricao: "Estrutura Geral. (Ex. A estrutura do prédio foi b em feita)", url: "imagens/palavras/e/65.jpg"},
    { palavra: "Estudo", url: "imagens/palavras/e/66.jpg"},
    { palavra: "Estupro", url: "imagens/palavras/e/67.jpg"},
    { palavra: "Ética", url: "imagens/palavras/e/68.jpg"},
    { palavra: "Evitar", url: "imagens/palavras/e/69.jpg"},
    { palavra: "Evolução", url: "imagens/palavras/e/70.jpg"},
    { palavra: "Exame", descricao: "Exame de sangue", url: "imagens/palavras/e/71.jpg"},
    { palavra: "Exame", descricao: "Exame clínico", url: "imagens/palavras/e/72.jpg"},
    { palavra: "Exame", descricao: "Exame radiológico", url: "imagens/palavras/e/73.jpg"},
    { palavra: "Exame", descricao: "Prova Final", url: "imagens/palavras/e/74.jpg"},
    { palavra: "Exclusão", url: "imagens/palavras/e/75.jpg"},
    { palavra: "Exercício", url: "imagens/palavras/e/76.jpg"},
    { palavra: "Exibid@", descricao: "Exibido", url: "imagens/palavras/e/77.jpg"},
    { palavra: "Exibid@", descricao: "Exibido", url: "imagens/palavras/e/78.jpg"},
    { palavra: "Experiência", url: "imagens/palavras/e/79.jpg"},
    { palavra: "Experimentar", url: "imagens/palavras/e/80.jpg"},
    { palavra: "Explicar", url: "imagens/palavras/e/81.jpg"},
    { palavra: "Expulsar", url: "imagens/palavras/e/82.jpg"},

    { palavra: "Fábrica", url: "imagens/palavras/f/1.jpg"},
    { palavra: "Fácil", url: "imagens/palavras/f/2.jpg"},
    { palavra: "Falar", url: "imagens/palavras/f/3.jpg"},
    { palavra: "Faculdade", url: "imagens/palavras/f/4.jpg"},
    { palavra: "Falecer", url: "imagens/palavras/f/5.jpg"},
    { palavra: "Fals@", url: "imagens/palavras/f/6.jpg"},
    { palavra: "Faltar", descricao: "Ausente. (Ex. Faltou um aluno para formar o  grupo)", url: "imagens/palavras/f/7.jpg"},
    { palavra: "Faltar", descricao: "Coisa. (Ex: Faltou água em casa)", url: "imagens/palavras/f/8.jpg"},
    { palavra: "Faltar", descricao: "Compromisso. (Ex: O funcionário faltou o trabalho p or causa de muita chuva)", url: "imagens/palavras/f/9.jpg"},
    { palavra: "Família", categoria: categorias.familia.nome, url: "imagens/palavras/f/10.jpg"},
    { palavra: "Famos@", url: "imagens/palavras/f/11.jpg"},
    { palavra: "Farmácia", url: "imagens/palavras/f/12.jpg"},
    { palavra: "Fazenda", url: "imagens/palavras/f/13.jpg"},
    { palavra: "Fazer", url: "imagens/palavras/f/14.jpg"},
    { palavra: "Febre", url: "imagens/palavras/f/15.jpg"},
    { palavra: "Fechar", url: "imagens/palavras/f/16.jpg"},
    { palavra: "Federal", url: "imagens/palavras/f/17.jpg"},
    { palavra: "Feijão", url: "imagens/palavras/f/18.jpg"},
    { palavra: "Fei@", url: "imagens/palavras/f/19.jpg"},
    { palavra: "Feira", url: "imagens/palavras/f/20.jpg"},
    { palavra: "Feliz", url: "imagens/palavras/f/21.jpg"},
    { palavra: "Feriado", url: "imagens/palavras/f/22.jpg"},
    { palavra: "Férias", url: "imagens/palavras/f/23.jpg"},
    { palavra: "Ferro", url: "imagens/palavras/f/24.jpg"},
    { palavra: "Festa", url: "imagens/palavras/f/25.jpg"},
    { palavra: "Fila", url: "imagens/palavras/f/27.jpg"},
    { palavra: "Filh@", url: "imagens/palavras/f/28.jpg"},
    { palavra: "Filme", url: "imagens/palavras/f/29.jpg"},
    { palavra: "Filosofia", categoria: categorias.disciplinas.nome, url: "imagens/palavras/f/30.jpg"},
    { palavra: "Fim", url: "imagens/palavras/f/31.jpg"},
    { palavra: "Fina", url: "imagens/palavras/f/32.jpg"},
    { palavra: "Financiar", url: "imagens/palavras/f/33.jpg"},
    { palavra: "Fingir", url: "imagens/palavras/f/34.jpg"},
    { palavra: "Fio", url: "imagens/palavras/f/35.jpg"},
    { palavra: "Fiscal", categoria: categorias.profissoes.nome, url: "imagens/palavras/f/36.jpg"},
    { palavra: "Física", categoria: categorias.disciplinas.nome, url: "imagens/palavras/f/37.jpg"},
    { palavra: "Fisioterapia", categoria: categorias.profissoes.nome, url: "imagens/palavras/f/38.jpg"},
    { palavra: "Fita adesiva", url: "imagens/palavras/f/39.jpg"},
    { palavra: "Ficar", descricao: "Manter-se. (Ex: Eu fiquei em casa ontem)", url: "imagens/palavras/f/40.jpg"},
    { palavra: "Ficar", descricao: "Namoricar. (Ex: Eu fiquei com um menino lindo hoje )", url: "imagens/palavras/f/41.jpg"},
    { palavra: "Ficar", descricao: "Permanecer. (Ex. Você deve ficar em casa, esperand o o eletricista)", url: "imagens/palavras/f/42.jpg"},
    { palavra: "Floresta", url: "imagens/palavras/f/43.jpg"},
    { palavra: "Foca", categoria: categorias.animais.nome, url: "imagens/palavras/f/44.jpg"},
    { palavra: "Fofoca", url: "imagens/palavras/f/45.jpg"},
    { palavra: "Fofoqueir@", url: "imagens/palavras/f/46.jpg"},
    { palavra: "Folga", url: "imagens/palavras/f/47.jpg"},
    { palavra: "Formar", url: "imagens/palavras/f/48.jpg"},
    { palavra: "Formiga",  categoria: categorias.animais.nome, url: "imagens/palavras/f/49.jpg"},
    { palavra: "Forte", descricao: "Forte", url: "imagens/palavras/f/50.jpg"},
    { palavra: "Forte", descricao: "Forte", url: "imagens/palavras/f/51.jpg"},
    { palavra: "Fórum", url: "imagens/palavras/f/52.jpg"},
    { palavra: "Frac@", url: "imagens/palavras/f/53.jpg"},
    { palavra: "Frio", url: "imagens/palavras/f/54.jpg"},
    { palavra: "Frente", url: "imagens/palavras/f/55.jpg"},
    { palavra: "Fruta", descricao: "Fruta", url: "imagens/palavras/f/56.jpg"},
    { palavra: "Fruta", descricao: "Fruta", url: "imagens/palavras/f/57.jpg"},
    { palavra: "Fumo", url: "imagens/palavras/f/58.jpg"},
    { palavra: "Fugir", url: "imagens/palavras/f/59.jpg"},
    { palavra: "Funcionar", url: "imagens/palavras/f/60.jpg"},
    { palavra: "Funcionári@", categoria: categorias.profissoes.nome, url: "imagens/palavras/f/61.jpg"},
    { palavra: "Fundar", url: "imagens/palavras/f/62.jpg"},
    { palavra: "Fundamental", url: "imagens/palavras/f/63.jpg"},
    { palavra: "Fundo", url: "imagens/palavras/f/64.jpg"},
    { palavra: "Furios@", url: "imagens/palavras/f/65.jpg"},
    { palavra: "Futebol", categoria: categorias.esportes.nome, url: "imagens/palavras/f/66.jpg"},
    { palavra: "Francesa", url: "imagens/palavras/f/67.jpg"},
    { palavra: "Frase", url: "imagens/palavras/f/68.jpg"},
    { palavra: "Foto    ", url: "imagens/palavras/f/69.jpg"},
    { palavra: "Filmagem", url: "imagens/palavras/f/70.jpg"},
    
    { palavra: "Gabarito", url: "imagens/palavras/g/1.jpg"},
    { palavra: "Gafanhoto", categoria: categorias.animais.nome, url: "imagens/palavras/g/2.jpg"},
    { palavra: "Galinha", categoria: categorias.animais.nome, url: "imagens/palavras/g/3.jpg"},
    { palavra: "Galo", categoria: categorias.animais.nome, url: "imagens/palavras/g/4.jpg"},
    { palavra: "Gangue", url: "imagens/palavras/g/5.jpg"},
    { palavra: "Ganhar", url: "imagens/palavras/g/6.jpg"},
    { palavra: "Garantia", url: "imagens/palavras/g/7.jpg"},
    { palavra: "Garçom", categoria: categorias.profissoes.nome, url: "imagens/palavras/g/8.jpg"},
    { palavra: "Gasolina", url: "imagens/palavras/g/9.jpg"},
    { palavra: "Gaúch@", url: "imagens/palavras/g/10.jpg"},
    { palavra: "Gasômetro", url: "imagens/palavras/g/11.jpg"},
    { palavra: "Gastar", url: "imagens/palavras/g/12.jpg"},
    { palavra: "Gente", url: "imagens/palavras/g/13.jpg"},
    { palavra: "Gat@", categoria: categorias.animais.nome, url: "imagens/palavras/g/14.jpg"},
    { palavra: "Gême@", url: "imagens/palavras/g/15.jpg"},
    { palavra: "Geografia", categoria: categorias.disciplinas.nome, url: "imagens/palavras/g/16.jpg"},
    { palavra: "Geral", url: "imagens/palavras/g/17.jpg"},
    { palavra: "Gerente", categoria: categorias.profissoes.nome, url: "imagens/palavras/g/18.jpg"},
    { palavra: "Ginásio", url: "imagens/palavras/g/19.jpg"},
    { palavra: "Ginástica", categoria: categorias.esportes.nome, url: "imagens/palavras/g/20.jpg"},
    { palavra: "Girafa", categoria: categorias.animais.nome, url: "imagens/palavras/g/21.jpg"},
    { palavra: "Ginecologia", categoria: categorias.profissoes.nome, url: "imagens/palavras/g/22.jpg"},
    { palavra: "Giz", url: "imagens/palavras/g/23.jpg"},
    { palavra: "Globo", url: "imagens/palavras/g/24.jpg"},
    { palavra: "Goiaba", categoria: categorias.frutas.nome, url: "imagens/palavras/g/25.jpg"},
    { palavra: "Gol", categoria: categorias.esportes.nome, url: "imagens/palavras/g/26.jpg"},
    { palavra: "Goleir@", categoria: categorias.esportes.nome, url: "imagens/palavras/g/27.jpg"},
    { palavra: "Golfe", categoria: categorias.esportes.nome, url: "imagens/palavras/g/28.jpg"},
    { palavra: "Golfinho", categoria: categorias.animais.nome, url: "imagens/palavras/g/29.jpg"},
    { palavra: "Gord@", url: "imagens/palavras/g/30.jpg"},
    { palavra: "Gostar", descricao: "Gostar (Ex: Eu gosto de você)", url: "imagens/palavras/g/31.jpg"},
    { palavra: "Gostar", descricao: "Gostar (Ex: Eu gosto de você)", url: "imagens/palavras/g/32.jpg"},
    { palavra: "Gostar-não", url: "imagens/palavras/g/33.jpg"},
    { palavra: "Gostos@", url: "imagens/palavras/g/34.jpg"},
    { palavra: "Governador@", categoria: categorias.profissoes.nome, url: "imagens/palavras/g/35.jpg"},
    { palavra: "Governo", url: "imagens/palavras/g/36.jpg"},
    { palavra: "Grampeador", url: "imagens/palavras/g/37.jpg"},
    { palavra: "Grande", url: "imagens/palavras/g/38.jpg"},
    { palavra: "Grátis", url: "imagens/palavras/g/39.jpg"},
    { palavra: "Gravidez", url: "imagens/palavras/g/40.jpg"},
    { palavra: "Gravar", url: "imagens/palavras/g/41.jpg"},
    { palavra: "Greve", url: "imagens/palavras/g/42.jpg"},
    { palavra: "Gripe", url: "imagens/palavras/g/43.jpg"},
    { palavra: "Gritar", url: "imagens/palavras/g/44.jpg"},
    { palavra: "Grosseir@", url: "imagens/palavras/g/45.jpg"},
    { palavra: "Grosso", url: "imagens/palavras/g/46.jpg"},
    { palavra: "Grudar", url: "imagens/palavras/g/47.jpg"},
    { palavra: "Grupo", url: "imagens/palavras/g/48.jpg"},
    { palavra: "Guaraná", categoria: categorias.frutas.nome, url: "imagens/palavras/g/49.jpg"},
    { palavra: "Guarda", url: "imagens/palavras/g/50.jpg"},
    { palavra: "Guardanapo", url: "imagens/palavras/g/51.jpg"},
    { palavra: "Guardar", url: "imagens/palavras/g/52.jpg"},
    { palavra: "Guerra", url: "imagens/palavras/g/53.jpg"},
    { palavra: "Guiar", url: "imagens/palavras/g/54.jpg"},
    
    { palavra: "Handebol", categoria: categorias.esportes.nome, url: "imagens/palavras/h/1.jpg"},
    { palavra: "Haver", url: "imagens/palavras/h/2.jpg"},
    { palavra: "Helicóptero", categoria: categorias.transportes.nome, url: "imagens/palavras/h/3.jpg"},
    { palavra: "Herança", url: "imagens/palavras/h/4.jpg"},
    { palavra: "Hiena", categoria: categorias.animais.nome, url: "imagens/palavras/h/5.jpg"},
    { palavra: "Hino", url: "imagens/palavras/h/6.jpg"},
    { palavra: "Hipismo", categoria: categorias.esportes.nome, url: "imagens/palavras/h/7.jpg"},
    { palavra: "Hipopótamo", categoria: categorias.animais.nome, url: "imagens/palavras/h/8.jpg"},
    { palavra: "História", categoria: categorias.disciplinas.nome, descricao: "Disciplina (Ex. Hoje teremos aulas de História)", url: "imagens/palavras/h/9.jpg"},
    { palavra: "História", descricao: "Narração ordenada e escrita dos eventos e fatos oco rridos no passado remoto ou recente", url: "imagens/palavras/h/10.jpg"},
    { palavra: "HIV", url: "imagens/palavras/h/11.jpg"},
    { palavra: "Hoje", url: "imagens/palavras/h/12.jpg"},
    { palavra: "Homem", url: "imagens/palavras/h/13.jpg"},
    { palavra: "Homenagem", url: "imagens/palavras/h/14.jpg"},
    { palavra: "Hora", url: "imagens/palavras/h/15.jpg"},
    { palavra: "Horrível", url: "imagens/palavras/h/16.jpg"},
    { palavra: "Hospital", url: "imagens/palavras/h/17.jpg"},
    { palavra: "Hotel", url: "imagens/palavras/h/18.jpg"},
    { palavra: "Humano", url: "imagens/palavras/h/19.jpg"},
    { palavra: "Humilde", url: "imagens/palavras/h/20.jpg"},
    
    { palavra: "Idade", url: "imagens/palavras/i/1.jpg"},
    { palavra: "Idéia", url: "imagens/palavras/i/2.jpg"},
    { palavra: "Identidade", descricao: "Identidade quanto ao sujeito (Ex. A cultura surda tem identidade própria)", url: "imagens/palavras/i/3.jpg"},
    { palavra: "Identidade", descricao: "Identidade documento (Ex. Você pode me mostrar sua  identidade?)", url: "imagens/palavras/i/4.jpg"},
    { palavra: "Idoso", url: "imagens/palavras/i/5.jpg"},
    { palavra: "Igreja", url: "imagens/palavras/i/6.jpg"},
    { palavra: "Igual", url: "imagens/palavras/i/7.jpg"},
    { palavra: "Igualmente", url: "imagens/palavras/i/8.jpg"},
    { palavra: "Ilha", url: "imagens/palavras/i/9.jpg"},
    { palavra: "Imagem", descricao: "Imagem da pessoa (Ex. As atitudes daquela mulher  transmitem uma boa imagem)", url: "imagens/palavras/i/10.jpg"},
    { palavra: "Imagem", descricao: "Imagem no papel", url: "imagens/palavras/i/11.jpg"},
    { palavra: "Imaginar", url: "imagens/palavras/i/12.jpg"},
    { palavra: "Importado", url: "imagens/palavras/i/13.jpg"},
    { palavra: "Importante", url: "imagens/palavras/i/14.jpg"},
    { palavra: "Impossível", url: "imagens/palavras/i/15.jpg"},
    { palavra: "Imposto", url: "imagens/palavras/i/16.jpg"},
    { palavra: "Imprimir", url: "imagens/palavras/i/17.jpg"},
    { palavra: "Inauguração", url: "imagens/palavras/i/18.jpg"},
    { palavra: "Inclusão", descricao: "Inclusão em geral", url: "imagens/palavras/i/19.jpg"},
    { palavra: "Inclusão", descricao: "Inclusão de uma pessoa só.", url: "imagens/palavras/i/20.jpg"},
    { palavra: "Infantil", url: "imagens/palavras/i/21.jpg"},
    { palavra: "Inferior", url: "imagens/palavras/i/22.jpg"},
    { palavra: "Influênciar (me)", url: "imagens/palavras/i/23.jpg"},
    { palavra: "Influênciar (te)", url: "imagens/palavras/i/24.jpg"},
    { palavra: "Informação", url: "imagens/palavras/i/25.jpg"},
    { palavra: "Informe-me", url: "imagens/palavras/i/26.jpg"},
    { palavra: "Informar-te", url: "imagens/palavras/i/27.jpg"},
    { palavra: "Informática", url: "imagens/palavras/i/28.jpg"},
    { palavra: "Início", url: "imagens/palavras/i/29.jpg"},
    { palavra: "Inimig@", url: "imagens/palavras/i/30.jpg"},
    { palavra: "Inscrição", url: "imagens/palavras/i/31.jpg"},
    { palavra: "Inteligente", url: "imagens/palavras/i/32.jpg"},
    { palavra: "Interessar", url: "imagens/palavras/i/33.jpg"},
    { palavra: "Interior", url: "imagens/palavras/i/34.jpg"},
    { palavra: "Intermediário", url: "imagens/palavras/i/35.jpg"},
    { palavra: "Internacional", url: "imagens/palavras/i/36.jpg"},
    { palavra: "Internet", url: "imagens/palavras/i/37.jpg"},
    { palavra: "Intérprete", categoria: categorias.profissoes.nome, url: "imagens/palavras/i/38.jpg"},
    { palavra: "Intervalo", url: "imagens/palavras/i/39.jpg"},
    { palavra: "Inveja", url: "imagens/palavras/i/40.jpg"},
    { palavra: "Inventar", url: "imagens/palavras/i/41.jpg"},
    { palavra: "Inverno", url: "imagens/palavras/i/42.jpg"},
    { palavra: "Ir", url: "imagens/palavras/i/43.jpg"},
    { palavra: "Irm@", categoria: categorias.familia.nome, url: "imagens/palavras/i/44.jpg"},
    
    { palavra: "Jantar", url: "imagens/palavras/j/1.jpg"},
    { palavra: "Javali", categoria: categorias.animais.nome, url: "imagens/palavras/j/3.jpg"},
    { palavra: "Já", url: "imagens/palavras/j/4.jpg"},
    { palavra: "Jogar", url: "imagens/palavras/j/5.jpg"},
    { palavra: "Jornal", url: "imagens/palavras/j/6.jpg"},
    { palavra: "Jovem", url: "imagens/palavras/j/7.jpg"},
    { palavra: "Junt@", url: "imagens/palavras/j/10.jpg"},
    { palavra: "Juros", url: "imagens/palavras/j/11.jpg"},
    { palavra: "Jacaré", categoria: categorias.animais.nome, url: "imagens/palavras/j/12.jpg"},
    { palavra: "Jeito", url: "imagens/palavras/j/13.jpg"},
    { palavra: "Judeu", url: "imagens/palavras/j/14.jpg"},
    { palavra: "Juiz@", categoria: categorias.profissoes.nome, url: "imagens/palavras/j/15.jpg"},
    { palavra: "Justiça", url: "imagens/palavras/j/16.jpg"},
    { palavra: "Jurar", url: "imagens/palavras/j/17.jpg"},
    
    { palavra: "Lá", url: "imagens/palavras/l/1.jpg"},
    { palavra: "Laboratório", url: "imagens/palavras/l/2.jpg"},
    { palavra: "Lado", url: "imagens/palavras/l/3.jpg"},
    { palavra: "Lagarto", categoria: categorias.animais.nome, url: "imagens/palavras/l/4.jpg"},
    { palavra: "Lagoa", url: "imagens/palavras/l/5.jpg"},
    { palavra: "Lágrima", url: "imagens/palavras/l/6.jpg"},
    { palavra: "Lamentar", url: "imagens/palavras/l/7.jpg"},
    { palavra: "Lanche", url: "imagens/palavras/l/8.jpg"},
    { palavra: "Lápis", url: "imagens/palavras/l/9.jpg"},
    { palavra: "Lápis de cor", url: "imagens/palavras/l/10.jpg"},
    { palavra: "Laranja",  descricao: "fruta", categoria: categorias.frutas.nome, url: "imagens/palavras/l/11.jpg"},
    { palavra: "Laranja",  descricao: "cor", categoria: categorias.cores.nome, url: "imagens/palavras/l/11.jpg"},
    { palavra: "Lagartixa", categoria: categorias.animais.nome, url: "imagens/palavras/l/12.jpg"},
    { palavra: "Largar", url: "imagens/palavras/l/13.jpg"},
    { palavra: "Lavar", descricao: "Lavar objetos  pequenos. (Ex:  Lavar roupa, louça)", url: "imagens/palavras/l/14.jpg"},
    { palavra: "Lavar", descricao: "Lavar qualquer objeto. (Ex: Lavar carro, vidro, pa rede)", url: "imagens/palavras/l/15.jpg"},
    { palavra: "Legendado", url: "imagens/palavras/l/16.jpg"},
    { palavra: "Leão", categoria: categorias.animais.nome, url: "imagens/palavras/l/17.jpg"},
    { palavra: "Legal", descricao: "Coisa ou pessoa boa. (Ex: Você é uma pessoa legal!)", url: "imagens/palavras/l/18.jpg"},
    { palavra: "Legal", descricao: "Tudo bem (Ex. Tudo legal com você?)", url: "imagens/palavras/l/19.jpg"},
    { palavra: "Lei", url: "imagens/palavras/l/20.jpg"},
    { palavra: "Leilão", url: "imagens/palavras/l/21.jpg"},
    { palavra: "Leite", url: "imagens/palavras/l/22.jpg"},
    { palavra: "Lembrar", url: "imagens/palavras/l/23.jpg"},
    { palavra: "Ler", url: "imagens/palavras/l/24.jpg"},
    { palavra: "Leste", categoria: categorias.pontosCardeais.nome, url: "imagens/palavras/l/25.jpg"},
    { palavra: "Letra", descricao: "Letra do alfabeto", url: "imagens/palavras/l/26.jpg"},
    { palavra: "Letras", descricao: "Disciplina de Letras", url: "imagens/palavras/l/27.jpg"},
    { palavra: "Levar", url: "imagens/palavras/l/28.jpg"},
    { palavra: "Licença", url: "imagens/palavras/l/29.jpg"},
    { palavra: "Leve", url: "imagens/palavras/l/30.jpg"},
    { palavra: "Libertar", url: "imagens/palavras/l/31.jpg"},
    { palavra: "Líder", descricao: "Pessoa de maior evidência em um partido político, numa comunidade ou coletividade.", url: "imagens/palavras/l/32.jpg"},
    { palavra: "Líder", descricao: "Chefe de uma turma, guia. Tipo representativo de um  grupo.", url: "imagens/palavras/l/33.jpg"},
    { palavra: "Limite", url: "imagens/palavras/l/34.jpg"},
    { palavra: "Limpar", descricao: "Limpar objetos pequenos. (Ex: Limpar louça, móveis)", url: "imagens/palavras/l/35.jpg"},
    { palavra: "Limpar", descricao: "Limpar qualquer objeto. (Ex: Limpar quarto, carro, vidro, parede)", url: "imagens/palavras/l/36.jpg"},
    { palavra: "Lis@", url: "imagens/palavras/l/37.jpg"},
    { palavra: "Língua", url: "imagens/palavras/l/38.jpg"},
    { palavra: "Linguagem", url: "imagens/palavras/l/39.jpg"},
    { palavra: "Literatura", categoria: categorias.disciplinas.nome, url: "imagens/palavras/l/40.jpg"},
    { palavra: "Linha", url: "imagens/palavras/l/41.jpg"},
    { palavra: "Liquidação", url: "imagens/palavras/l/42.jpg"},
    { palavra: "Livre", url: "imagens/palavras/l/43.jpg"},
    { palavra: "Livro", url: "imagens/palavras/l/44.jpg"},
    { palavra: "Lob@", categoria: categorias.animais.nome, url: "imagens/palavras/l/45.jpg"},
    { palavra: "Locadora", url: "imagens/palavras/l/46.jpg"},
    { palavra: "Local", url: "imagens/palavras/l/47.jpg"},
    { palavra: "Loja", url: "imagens/palavras/l/48.jpg"},
    { palavra: "Longe", descricao: "Perspectiva", url: "imagens/palavras/l/49.jpg"},
    { palavra: "Longe", descricao: "Perspectiva-Muito longe", url: "imagens/palavras/l/50.jpg"},
    { palavra: "Louc@", url: "imagens/palavras/l/51.jpg"},
    { palavra: "Lua", url: "imagens/palavras/l/52.jpg"},
    { palavra: "Lugar", url: "imagens/palavras/l/53.jpg"},
    { palavra: "Lucro", url: "imagens/palavras/l/54.jpg"},
    { palavra: "Lula", categoria: categorias.animais.nome, url: "imagens/palavras/l/55.jpg"},
    { palavra: "Luta livre", categoria: categorias.esportes.nome, url: "imagens/palavras/l/56.jpg"},
    { palavra: "Lutar", url: "imagens/palavras/l/57.jpg"},
    { palavra: "Luterana", url: "imagens/palavras/l/58.jpg"},
    { palavra: "Luxo", url: "imagens/palavras/l/59.jpg"},
    
    { palavra: "Maçã", categoria: categorias.frutas.nome, url: "imagens/palavras/m/1.jpg"},
    { palavra: "Macaco", categoria: categorias.animais.nome, url: "imagens/palavras/m/2.jpg"},
    { palavra: "Machucar", url: "imagens/palavras/m/3.jpg"},
    { palavra: "Madeira", url: "imagens/palavras/m/4.jpg"},
    { palavra: "Madrasta", categoria: categorias.familia.nome, url: "imagens/palavras/m/5.jpg"},
    { palavra: "Madrinha", categoria: categorias.familia.nome, url: "imagens/palavras/m/6.jpg"},
    { palavra: "Madrugada", url: "imagens/palavras/m/7.jpg"},
    { palavra: "Mãe", categoria: categorias.familia.nome, url: "imagens/palavras/m/8.jpg"},
    { palavra: "Máfia", url: "imagens/palavras/m/9.jpg"},
    { palavra: "Magistério", categoria: categorias.profissoes.nome, url: "imagens/palavras/m/10.jpg"},
    { palavra: "Magoar", url: "imagens/palavras/m/11.jpg"},
    { palavra: "Mais", descricao: "Exagero (Ex. Dois alunos brigam, um continua faland o mais e não para)", url: "imagens/palavras/m/13.jpg"},
    { palavra: "Mais", descricao: "Aumentar (Ex. O Plano de aula precisa mais objetivo)", url: "imagens/palavras/m/14.jpg"},
    { palavra: "Mais", descricao: "Superlativo (Ex. Ela é mais bonita do que a irmã)", url: "imagens/palavras/m/15.jpg"},
    { palavra: "Mais", descricao: "Quantidade (Ex. Quero mais carne)", url: "imagens/palavras/m/16.jpg"},
    { palavra: "Mais", descricao: "Acréscimo (Ex: Acresceu o meu salário, porque trabalhei mais de 8 horas)", url: "imagens/palavras/m/17.jpg"},
    { palavra: "Mais", descricao: "Somar (Ex: 4+4)", url: "imagens/palavras/m/18.jpg"},
    { palavra: "Mais ou menos", url: "imagens/palavras/m/19.jpg"},
    { palavra: "Mal", url: "imagens/palavras/m/20.jpg"},
    { palavra: "Malvad@", url: "imagens/palavras/m/21.jpg"},
    { palavra: "Mamar", url: "imagens/palavras/m/22.jpg"},
    { palavra: "Mandar", url: "imagens/palavras/m/23.jpg"},
    { palavra: "Manga", categoria: categorias.frutas.nome, url: "imagens/palavras/m/24.jpg"},
    { palavra: "Manhã", url: "imagens/palavras/m/25.jpg"},
    { palavra: "Máquina", url: "imagens/palavras/m/26.jpg"},
    { palavra: "Maracujá", categoria: categorias.frutas.nome, url: "imagens/palavras/m/27.jpg"},
    { palavra: "Marcar", url: "imagens/palavras/m/28.jpg"},
    { palavra: "Mas", url: "imagens/palavras/m/30.jpg"},
    { palavra: "Massa / Macarrão", url: "imagens/palavras/m/31.jpg"},
    { palavra: "Matemática", categoria: categorias.disciplinas.nome, url: "imagens/palavras/m/32.jpg"},
    { palavra: "Material", url: "imagens/palavras/m/33.jpg"},
    { palavra: "Matrícula", url: "imagens/palavras/m/34.jpg"},
    { palavra: "Mau", url: "imagens/palavras/m/35.jpg"},
    { palavra: "Me@", url: "imagens/palavras/m/36.jpg"},
    { palavra: "Medalha", url: "imagens/palavras/m/37.jpg"},
    { palavra: "Médico", categoria: categorias.profissoes.nome, url: "imagens/palavras/m/38.jpg"},
    { palavra: "Medo", url: "imagens/palavras/m/39.jpg"},
    { palavra: "Meia", url: "imagens/palavras/m/40.jpg"},
    { palavra: "Meio", url: "imagens/palavras/m/41.jpg"},
    { palavra: "Mel", url: "imagens/palavras/m/42.jpg"},
    { palavra: "Melancia", categoria: categorias.frutas.nome, url: "imagens/palavras/m/43.jpg"},
    { palavra: "Melhor", url: "imagens/palavras/m/44.jpg"},
    { palavra: "Menina", url: "imagens/palavras/m/45.jpg"},
    { palavra: "Menino", url: "imagens/palavras/m/46.jpg"},
    { palavra: "Menos", url: "imagens/palavras/m/47.jpg"},
    { palavra: "Mensagem", url: "imagens/palavras/m/48.jpg"},
    { palavra: "Menstruação", url: "imagens/palavras/m/49.jpg"},
    { palavra: "Mental", url: "imagens/palavras/m/50.jpg"},
    { palavra: "Mentir", url: "imagens/palavras/m/51.jpg"},
    { palavra: "Merecer", url: "imagens/palavras/m/52.jpg"},
    { palavra: "Merenda", url: "imagens/palavras/m/53.jpg"},
    { palavra: "Mês", url: "imagens/palavras/m/54.jpg"},
    { palavra: "Mesa", url: "imagens/palavras/m/55.jpg"},
    { palavra: "Metodologia", url: "imagens/palavras/m/56.jpg"},
    { palavra: "Metrô", categoria: categorias.transportes.nome, url: "imagens/palavras/m/57.jpg"},
    { palavra: "Milagre", url: "imagens/palavras/m/58.jpg"},
    { palavra: "Milho", url: "imagens/palavras/m/59.jpg"},
    { palavra: "Minhoca", categoria: categorias.animais.nome, url: "imagens/palavras/m/60.jpg"},
    { palavra: "Ministro", categoria: categorias.profissoes.nome, url: "imagens/palavras/m/61.jpg"},
    { palavra: "Missa", url: "imagens/palavras/m/62.jpg"},
    { palavra: "Modelo", descricao: "Modelo Profissional", url: "imagens/palavras/m/63.jpg"},
    { palavra: "Modelo", descricao: "Modelo = Referência", url: "imagens/palavras/m/64.jpg"},
    { palavra: "Momento", url: "imagens/palavras/m/65.jpg"},
    { palavra: "Monitor@", url: "imagens/palavras/m/66.jpg"},
    { palavra: "Montanha", url: "imagens/palavras/m/67.jpg"},
    { palavra: "Morcego", categoria: categorias.animais.nome, url: "imagens/palavras/m/68.jpg"},
    { palavra: "Morte", url: "imagens/palavras/m/69.jpg"},
    { palavra: "Mosca", categoria: categorias.animais.nome, url: "imagens/palavras/m/70.jpg"},
    { palavra: "Mosquito", categoria: categorias.animais.nome, url: "imagens/palavras/m/71.jpg"},
    { palavra: "Motel", url: "imagens/palavras/m/72.jpg"},
    { palavra: "Motocicleta", categoria: categorias.transportes.nome, url: "imagens/palavras/m/73.jpg"},
    { palavra: "Motor", url: "imagens/palavras/m/74.jpg"},
    { palavra: "Mudar", descricao: "Adiar. Deslocar (Ex. Mudamos a data da reunião. O professor mudou de casa)", url: "imagens/palavras/m/75.jpg"},
    { palavra: "Mudar", descricao: "Alterar. (Ex. Ele mudou o titulo do livro)", url: "imagens/palavras/m/76.jpg"},
    { palavra: "Muito", url: "imagens/palavras/m/77.jpg"},
    { palavra: "Mulher", url: "imagens/palavras/m/78.jpg"},
    { palavra: "Multa", url: "imagens/palavras/m/79.jpg"},
    { palavra: "Municipal", url: "imagens/palavras/m/80.jpg"},
    { palavra: "Muro", url: "imagens/palavras/m/81.jpg"},
    { palavra: "Museu", url: "imagens/palavras/m/82.jpg"},
    { palavra: "Música", categoria: categorias.disciplinas.nome, url: "imagens/palavras/m/83.jpg"},

    { palavra: "Nada", descricao: "Nenhuma coisa. (Ex: Estou com fome e não há nada na  geladeira)", url: "imagens/palavras/n/1.jpg"},
    { palavra: "Nada", descricao: "Idem nada. (Ex: Quem não estudou nada para prova?)", url: "imagens/palavras/n/2.jpg"},
    { palavra: "Nadar", categoria: categorias.esportes.nome, url: "imagens/palavras/n/3.jpg"},
    { palavra: "Namorad@", categoria: categorias.familia.nome, url: "imagens/palavras/n/4.jpg"},
    { palavra: "Não", url: "imagens/palavras/n/5.jpg"},
    { palavra: "Nariz", url: "imagens/palavras/n/6.jpg"},
    { palavra: "Nascer", url: "imagens/palavras/n/7.jpg"},
    { palavra: "Natal", url: "imagens/palavras/n/8.jpg"},
    { palavra: "Natural", url: "imagens/palavras/n/9.jpg"},
    { palavra: "Natureza", url: "imagens/palavras/n/10.jpg"},
    { palavra: "Navio", categoria: categorias.transportes.nome, url: "imagens/palavras/n/11.jpg"},
    { palavra: "Neblina", url: "imagens/palavras/n/12.jpg"},
    { palavra: "Necessitar", url: "imagens/palavras/n/13.jpg"},
    { palavra: "Negócio", url: "imagens/palavras/n/14.jpg"},
    { palavra: "Negro", url: "imagens/palavras/n/15.jpg"},
    { palavra: "Nojo", url: "imagens/palavras/n/16.jpg"},
    { palavra: "Noite", url: "imagens/palavras/n/17.jpg"},
    { palavra: "Noiv@", categoria: categorias.familia.nome, url: "imagens/palavras/n/18.jpg"},
    { palavra: "Nome", url: "imagens/palavras/n/19.jpg"},
    { palavra: "Nordeste", url: "imagens/palavras/n/20.jpg"},
    { palavra: "Normal", url: "imagens/palavras/n/21.jpg"},
    { palavra: "Norte", categoria: categorias.pontosCardeais.nome, url: "imagens/palavras/n/22.jpg"},
    { palavra: "Nós / Noss@", url: "imagens/palavras/n/23.jpg"},
    { palavra: "Nós", descricao: "Pronome pessoal feminino ou masculino da 1ª pessoa do plural. Este é no dual que o sinal composto form ado pelo sinal para a respectiva pessoa do discurso, existe trial no nº 98, quatrial  e grupo.", url: "imagens/palavras/n/24.jpg"},
    { palavra: "Nós", descricao: "trial", url: "imagens/palavras/n/25.jpg"},
    { palavra: "Nós", descricao: "quatrial", url: "imagens/palavras/n/26.jpg"},
    { palavra: "Nós-todos", descricao: "Pronome pessoal plural feminino ou masculino da 1ª pessoa do plural. Este é toda pessoa do discurso.", url: "imagens/palavras/n/27.jpg"},
    { palavra: "Notícia", url: "imagens/palavras/n/28.jpg"},
    { palavra: "Nov@", descricao: "Existe há pouco tempo. Que tem pouco uso. Recém-che gado (a).(Ex: comprei uma blusa nova)", url: "imagens/palavras/n/29.jpg"},
    { palavra: "Nov@", descricao: "Pessoa. (ex: Aquela mulher é nova para ser casada)", url: "imagens/palavras/n/30.jpg"},
    { palavra: "Novela", url: "imagens/palavras/n/31.jpg"},
    { palavra: "Novidade", url: "imagens/palavras/n/33.jpg"},
    { palavra: "Nudismo", url: "imagens/palavras/n/34.jpg"},
    { palavra: "Número", url: "imagens/palavras/n/35.jpg"},
    { palavra: "Nunca", url: "imagens/palavras/n/36.jpg"},
    { palavra: "Nunca mais", url: "imagens/palavras/n/37.jpg"},
    { palavra: "Nuvem", url: "imagens/palavras/n/38.jpg"},
    
    { palavra: "Oceano", url: "imagens/palavras/o/1.jpg"},
    { palavra: "Obedecer-te", url: "imagens/palavras/o/2.jpg"},
    { palavra: "Obedecer-me", url: "imagens/palavras/o/3.jpg"},
    { palavra: "Objetivo", url: "imagens/palavras/o/4.jpg"},
    { palavra: "Objeto", url: "imagens/palavras/o/5.jpg"},
    { palavra: "Obrar", url: "imagens/palavras/o/6.jpg"},
    { palavra: "Obrigad@", url: "imagens/palavras/o/7.jpg"},
    { palavra: "Obrigar", url: "imagens/palavras/o/8.jpg"},
    { palavra: "Observar", url: "imagens/palavras/o/9.jpg"},
    { palavra: "Óculos", url: "imagens/palavras/o/10.jpg"},
    { palavra: "Ocupado", url: "imagens/palavras/o/11.jpg"},
    { palavra: "Odiar", url: "imagens/palavras/o/12.jpg"},
    { palavra: "Oeste", categoria: categorias.pontosCardeais.nome,  url: "imagens/palavras/o/13.jpg"},
    { palavra: "Oficial", url: "imagens/palavras/o/14.jpg"},
    { palavra: "Oficina", url: "imagens/palavras/o/15.jpg"},
    { palavra: "Olhar", url: "imagens/palavras/o/16.jpg"},
    { palavra: "Olho", url: "imagens/palavras/o/17.jpg"},
    { palavra: "Olimpíada", categoria: categorias.esportes.nome, url: "imagens/palavras/o/18.jpg"},
    { palavra: "Onça", categoria: categorias.animais.nome, url: "imagens/palavras/o/19.jpg"},
    { palavra: "Onde", url: "imagens/palavras/o/20.jpg"},
    { palavra: "Ônibus", categoria: categorias.transportes.nome, url: "imagens/palavras/o/21.jpg"},
    { palavra: "Ontem", url: "imagens/palavras/o/22.jpg"},
    { palavra: "Operar", url: "imagens/palavras/o/23.jpg"},
    { palavra: "Opinião", descricao: "Opinião de pessoa surda.", url: "imagens/palavras/o/24.jpg"},
    { palavra: "Opinião", descricao: "Opinião de pessoa ouvinte.", url: "imagens/palavras/o/25.jpg"},
    { palavra: "Oportunidade", url: "imagens/palavras/o/26.jpg"},
    { palavra: "Oral", url: "imagens/palavras/o/27.jpg"},
    { palavra: "Ordem", url: "imagens/palavras/o/28.jpg"},
    { palavra: "Orelha", url: "imagens/palavras/o/29.jpg"},
    { palavra: "Orgulhar", url: "imagens/palavras/o/30.jpg"},
    { palavra: "Osso", url: "imagens/palavras/o/31.jpg"},
    { palavra: "Ótim@", url: "imagens/palavras/o/32.jpg"},
    { palavra: "Ouro", url: "imagens/palavras/o/33.jpg"},
    { palavra: "Outr@", url: "imagens/palavras/o/34.jpg"},
    { palavra: "Ouvir", url: "imagens/palavras/o/36.jpg"},
    { palavra: "Ovelha", categoria: categorias.animais.nome, url: "imagens/palavras/o/37.jpg"},
    
    { palavra: "Paciência", url: "imagens/palavras/p/1.jpg"},
    { palavra: "Padrasto", categoria: categorias.familia.nome, url: "imagens/palavras/p/2.jpg"},
    { palavra: "Padre", url: "imagens/palavras/p/3.jpg"},
    { palavra: "Padrinho", categoria: categorias.familia.nome, url: "imagens/palavras/p/4.jpg"},
    { palavra: "Pagar", url: "imagens/palavras/p/5.jpg"},
    { palavra: "Pai", categoria: categorias.familia.nome, url: "imagens/palavras/p/6.jpg"},
    { palavra: "País", url: "imagens/palavras/p/7.jpg"},
    { palavra: "Palavra", url: "imagens/palavras/p/8.jpg"},
    { palavra: "Palavrão", url: "imagens/palavras/p/9.jpg"},
    { palavra: "Palestra", url: "imagens/palavras/p/10.jpg"},
    { palavra: "Pão", url: "imagens/palavras/p/11.jpg"},
    { palavra: "Papel", url: "imagens/palavras/p/12.jpg"},
    { palavra: "Parabéns", url: "imagens/palavras/p/13.jpg"},
    { palavra: "Parada", url: "imagens/palavras/p/14.jpg"},
    { palavra: "Parecer", url: "imagens/palavras/p/15.jpg"},
    { palavra: "Participar", url: "imagens/palavras/p/16.jpg"},
    { palavra: "Particular", url: "imagens/palavras/p/17.jpg"},
    { palavra: "Passado", url: "imagens/palavras/p/18.jpg"},
    { palavra: "Passagem", url: "imagens/palavras/p/19.jpg"},
    { palavra: "Passaporte", url: "imagens/palavras/p/20.jpg"},
    { palavra: "Passar", descricao: "Atravessar (Ex. A mulher passou do lado do cachorro)", url: "imagens/palavras/p/21.jpg"},
    { palavra: "Passar", descricao: "Alisar (Ex. A esposa dedicada passa a roupa do marido).", url: "imagens/palavras/p/22.jpg"},
    { palavra: "Pássaro", categoria: categorias.animais.nome, url: "imagens/palavras/p/23.jpg"},
    { palavra: "Passear", url: "imagens/palavras/p/24.jpg"},
    { palavra: "Pastor", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/25.jpg"},
    { palavra: "Pato", categoria: categorias.animais.nome, url: "imagens/palavras/p/26.jpg"},
    { palavra: "Pecado", url: "imagens/palavras/p/27.jpg"},
    { palavra: "Pegar", url: "imagens/palavras/p/28.jpg"},
    { palavra: "Peito", url: "imagens/palavras/p/29.jpg"},
    { palavra: "Peixe", categoria: categorias.animais.nome, url: "imagens/palavras/p/30.jpg"},
    { palavra: "Pele", url: "imagens/palavras/p/31.jpg"},
    { palavra: "Pensão", url: "imagens/palavras/p/32.jpg"},
    { palavra: "Pensar", url: "imagens/palavras/p/33.jpg"},
    { palavra: "Pequeno", url: "imagens/palavras/p/34.jpg"},
    { palavra: "Pêra", categoria: categorias.frutas.nome, url: "imagens/palavras/p/35.jpg"},
    { palavra: "Perceber-me", url: "imagens/palavras/p/36.jpg"},
    { palavra: "Perceber-te", url: "imagens/palavras/p/37.jpg"},
    { palavra: "Perder", url: "imagens/palavras/p/38.jpg"},
    { palavra: "Perfeito", url: "imagens/palavras/p/39.jpg"},
    { palavra: "Perguntar-me", url: "imagens/palavras/p/40.jpg"},
    { palavra: "Perguntar-te", url: "imagens/palavras/p/41.jpg"},
    { palavra: "Perto", url: "imagens/palavras/p/42.jpg"},
    { palavra: "Peru", categoria: categorias.animais.nome, url: "imagens/palavras/p/43.jpg"},
    { palavra: "Pesado", url: "imagens/palavras/p/44.jpg"},
    { palavra: "Pesquisar", url: "imagens/palavras/p/45.jpg"},
    { palavra: "Pessoa", url: "imagens/palavras/p/46.jpg"},
    { palavra: "Piada", url: "imagens/palavras/p/47.jpg"},
    { palavra: "Pingüim", categoria: categorias.animais.nome, url: "imagens/palavras/p/48.jpg"},
    { palavra: "Pior", url: "imagens/palavras/p/49.jpg"},
    { palavra: "Pintar", descricao: "Pintar paredes", url: "imagens/palavras/p/50.jpg"},
    { palavra: "Pintar", descricao: "Pintar quadros", url: "imagens/palavras/p/51.jpg"},
    { palavra: "Pobre", url: "imagens/palavras/p/52.jpg"},
    { palavra: "Poder", url: "imagens/palavras/p/53.jpg"},
    { palavra: "Poder-não", url: "imagens/palavras/p/54.jpg"},
    { palavra: "Poesia", url: "imagens/palavras/p/55.jpg"},
    { palavra: "Polícia", url: "imagens/palavras/p/56.jpg"},
    { palavra: "Político", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/57.jpg"},
    { palavra: "Polvo", categoria: categorias.animais.nome, url: "imagens/palavras/p/58.jpg"},
    { palavra: "Pomba", categoria: categorias.animais.nome, url: "imagens/palavras/p/59.jpg"},
    { palavra: "Ponto", url: "imagens/palavras/p/60.jpg"},
    { palavra: "Por exemplo", url: "imagens/palavras/p/61.jpg"},
    { palavra: "Porcaria", url: "imagens/palavras/p/62.jpg"},
    { palavra: "Porcentagem", url: "imagens/palavras/p/63.jpg"},
    { palavra: "Porco", categoria: categorias.animais.nome, url: "imagens/palavras/p/64.jpg"},
    { palavra: "Por que", url: "imagens/palavras/p/65.jpg"},
    { palavra: "Português", categoria: categorias.disciplinas.nome, url: "imagens/palavras/p/66.jpg"},
    { palavra: "Pós-Graduado", url: "imagens/palavras/p/67.jpg"},
    { palavra: "Positivo", url: "imagens/palavras/p/68.jpg"},
    { palavra: "Possível", url: "imagens/palavras/p/69.jpg"},
    { palavra: "Posto", url: "imagens/palavras/p/70.jpg"},
    { palavra: "Pouco", url: "imagens/palavras/p/71.jpg"},
    { palavra: "Poupança", url: "imagens/palavras/p/72.jpg"},
    { palavra: "Povo", url: "imagens/palavras/p/73.jpg"},
    { palavra: "Praça", url: "imagens/palavras/p/74.jpg"},
    { palavra: "Praia", url: "imagens/palavras/p/75.jpg"},
    { palavra: "Prática", url: "imagens/palavras/p/76.jpg"},
    { palavra: "Prazer", url: "imagens/palavras/p/77.jpg"},
    { palavra: "Precisar", url: "imagens/palavras/p/78.jpg"},
    { palavra: "Preço", url: "imagens/palavras/p/79.jpg"},
    { palavra: "Preconceito", url: "imagens/palavras/p/80.jpg"},
    { palavra: "Prédio", url: "imagens/palavras/p/81.jpg"},
    { palavra: "Prefeit@", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/82.jpg"},
    { palavra: "Preferir", url: "imagens/palavras/p/83.jpg"},
    { palavra: "Preocupar", url: "imagens/palavras/p/84.jpg"},
    { palavra: "Preparar", url: "imagens/palavras/p/85.jpg"},
    { palavra: "Presente", url: "imagens/palavras/p/86.jpg"},
    { palavra: "Preservativo", url: "imagens/palavras/p/87.jpg"},
    { palavra: "Presidente", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/88.jpg"},
    { palavra: "Presídio", url: "imagens/palavras/p/89.jpg"},
    { palavra: "Preto", categoria: categorias.cores.nome, url: "imagens/palavras/p/90.jpg"},
    { palavra: "Prim@", categoria: categorias.familia.nome, url: "imagens/palavras/p/91.jpg"},
    { palavra: "Primavera", url: "imagens/palavras/p/92.jpg"},
    { palavra: "Principal", url: "imagens/palavras/p/93.jpg"},
    { palavra: "Problema", url: "imagens/palavras/p/94.jpg"},
    { palavra: "Processo", url: "imagens/palavras/p/95.jpg"},
    { palavra: "Procurar", url: "imagens/palavras/p/96.jpg"},
    { palavra: "Professor@", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/97.jpg"},
    { palavra: "Profissão", url: "imagens/palavras/p/98.jpg"},
    { palavra: "Profundo", url: "imagens/palavras/p/99.jpg"},
    { palavra: "Programa", url: "imagens/palavras/p/100.jpg"},
    { palavra: "Proibir", url: "imagens/palavras/p/101.jpg"},
    { palavra: "Projeto", url: "imagens/palavras/p/102.jpg"},
    { palavra: "Prometer", url: "imagens/palavras/p/103.jpg"},
    { palavra: "Pronto", url: "imagens/palavras/p/104.jpg"},
    { palavra: "Propósito", url: "imagens/palavras/p/105.jpg"},
    { palavra: "Proposta", url: "imagens/palavras/p/106.jpg"},
    { palavra: "Própri@", url: "imagens/palavras/p/107.jpg"},
    { palavra: "Prorrogação", url: "imagens/palavras/p/108.jpg"},
    { palavra: "Proteger", url: "imagens/palavras/p/109.jpg"},
    { palavra: "Prova", descricao: "Fazer prova na escola. (Ex: hoje têm prova de LS)", url: "imagens/palavras/p/110.jpg"},
    { palavra: "Provar", descricao: "Documento ou material que serve para provar a vera cidade dos fatos. (Ex: Eu não estou mentindo eu tenho provas)", url: "imagens/palavras/p/111.jpg"},
    { palavra: "Provocar", url: "imagens/palavras/p/112.jpg"},
    { palavra: "Próximo", url: "imagens/palavras/p/113.jpg"},
    { palavra: "Psicologia", categoria: categorias.profissoes.nome, url: "imagens/palavras/p/114.jpg"},
    { palavra: "Pulga e piolho", categoria: categorias.animais.nome, url: "imagens/palavras/p/115.jpg"},
    { palavra: "Pur@", url: "imagens/palavras/p/116.jpg"},
    { palavra: "Puxar", url: "imagens/palavras/p/117.jpg"},    

    { palavra: "Quadro", url: "imagens/palavras/q/1.jpg"},
    { palavra: "Qual", url: "imagens/palavras/q/2.jpg"},
    { palavra: "Qual de dois", url: "imagens/palavras/q/3.jpg"},
    { palavra: "Qualidade", url: "imagens/palavras/q/4.jpg"},
    { palavra: "Qualquer", url: "imagens/palavras/q/5.jpg"},
    { palavra: "Quando", descricao: "Tempo Presente em frase interrogativa. (Ex: Quando  vamos estudar?)", url: "imagens/palavras/q/6.jpg"},
    { palavra: "Quando", descricao: "Tempo Passado em frase interrogativa. (Ex: Quando você nasceu?)", url: "imagens/palavras/q/7.jpg"},
    { palavra: "Quando", descricao: "Tempo Futuro em frase interrogativa. (Ex: Quando você vai na minha casa?)", url: "imagens/palavras/q/8.jpg"},
    { palavra: "Quanto", url: "imagens/palavras/q/9.jpg"},
    { palavra: "Quartel", url: "imagens/palavras/q/11.jpg"},
    { palavra: "Quarto", url: "imagens/palavras/q/12.jpg"},
    { palavra: "Quase", url: "imagens/palavras/q/13.jpg"},
    { palavra: "Quebrar", url: "imagens/palavras/q/14.jpg"},
    { palavra: "Queimar", url: "imagens/palavras/q/15.jpg"},
    { palavra: "Quem", url: "imagens/palavras/q/16.jpg"},
    { palavra: "Quente", url: "imagens/palavras/q/17.jpg"},
    { palavra: "Querer", url: "imagens/palavras/q/18.jpg"},
    { palavra: "Querer-não", url: "imagens/palavras/q/19.jpg"},
    { palavra: "Questionar", url: "imagens/palavras/q/20.jpg"},
    { palavra: "Quiet@", url: "imagens/palavras/q/21.jpg"},
    { palavra: "Quilo", url: "imagens/palavras/q/22.jpg"},
    { palavra: "Quilometro", url: "imagens/palavras/q/23.jpg"},
    { palavra: "Química", categoria: categorias.disciplinas.nome, url: "imagens/palavras/q/24.jpg"},
        
    { palavra: "Rádio", url: "imagens/palavras/r/1.jpg"},
    { palavra: "Raio", url: "imagens/palavras/r/2.jpg"},
    { palavra: "Raio-X", url: "imagens/palavras/r/3.jpg"},
    { palavra: "Raiva", url: "imagens/palavras/r/4.jpg"},
    { palavra: "Raro", descricao: "Que quase não existe.", url: "imagens/palavras/r/5.jpg"},
    { palavra: "Raro", descricao: "Que existem poucos.", url: "imagens/palavras/r/6.jpg"},
    { palavra: "Raspar", descricao: "Raspar cabelos.", url: "imagens/palavras/r/7.jpg"},
    { palavra: "Raspar", descricao: "Raspar objetos, comida.", url: "imagens/palavras/r/8.jpg"},
    { palavra: "Rato", categoria: categorias.animais.nome, url: "imagens/palavras/r/9.jpg"},
    { palavra: "Razão", url: "imagens/palavras/r/10.jpg"},
    { palavra: "Realmente", url: "imagens/palavras/r/11.jpg"},
    { palavra: "Receber", url: "imagens/palavras/r/12.jpg"},
    { palavra: "Reciclagem", url: "imagens/palavras/r/13.jpg"},
    { palavra: "Reclamar", url: "imagens/palavras/r/14.jpg"},
    { palavra: "Recuperação", url: "imagens/palavras/r/15.jpg"},
    { palavra: "Recurso humano", url: "imagens/palavras/r/16.jpg"},
    { palavra: "Redação", url: "imagens/palavras/r/17.jpg"},
    { palavra: "Rede", descricao: "Rede de computador", url: "imagens/palavras/r/18.jpg"},
    { palavra: "Rede", descricao: "Rede de dormir", url: "imagens/palavras/r/19.jpg"},
    { palavra: "Reforçar", url: "imagens/palavras/r/20.jpg"},
    { palavra: "Reformar", url: "imagens/palavras/r/21.jpg"},
    { palavra: "Região", url: "imagens/palavras/r/22.jpg"},
    { palavra: "Regra", url: "imagens/palavras/r/23.jpg"},
    { palavra: "Régua", url: "imagens/palavras/r/24.jpg"},
    { palavra: "Regulamento", url: "imagens/palavras/r/25.jpg"},
    { palavra: "Relacionar", url: "imagens/palavras/r/26.jpg"},
    { palavra: "Relatório", url: "imagens/palavras/r/27.jpg"},
    { palavra: "Religião", url: "imagens/palavras/r/28.jpg"},
    { palavra: "Remédio", url: "imagens/palavras/r/29.jpg"},
    { palavra: "Remo", url: "imagens/palavras/r/30.jpg"},
    { palavra: "Repetir", url: "imagens/palavras/r/31.jpg"},
    { palavra: "Repórter", categoria: categorias.profissoes.nome, url: "imagens/palavras/r/32.jpg"},
    { palavra: "Representar", url: "imagens/palavras/r/33.jpg"},
    { palavra: "Reprovar", url: "imagens/palavras/r/34.jpg"},
    { palavra: "República", url: "imagens/palavras/r/35.jpg"},
    { palavra: "Reservar", url: "imagens/palavras/r/36.jpg"},
    { palavra: "Resolver", url: "imagens/palavras/r/37.jpg"},
    { palavra: "Respeitar-me", url: "imagens/palavras/r/38.jpg"},
    { palavra: "Respeitar-te", url: "imagens/palavras/r/39.jpg"},
    { palavra: "Respirar", url: "imagens/palavras/r/40.jpg"},
    { palavra: "Responder-me", url: "imagens/palavras/r/41.jpg"},
    { palavra: "Responder-te", url: "imagens/palavras/r/42.jpg"},
    { palavra: "Responsável", url: "imagens/palavras/r/43.jpg"},
    { palavra: "Restaurante", descricao: "Restaurante", url: "imagens/palavras/r/44.jpg"},
    { palavra: "Restaurante", descricao: "Restaurante", url: "imagens/palavras/r/45.jpg"},
    { palavra: "Resumir", url: "imagens/palavras/r/46.jpg"},
    { palavra: "Resultado", url: "imagens/palavras/r/47.jpg"},
    { palavra: "Retirar", url: "imagens/palavras/r/48.jpg"},
    { palavra: "Reunião", url: "imagens/palavras/r/49.jpg"},
    { palavra: "Revista", url: "imagens/palavras/r/50.jpg"},
    { palavra: "Revolução", url: "imagens/palavras/r/51.jpg"},
    { palavra: "Rinoceronte", categoria: categorias.animais.nome, url: "imagens/palavras/r/52.jpg"},
    { palavra: "Rir", url: "imagens/palavras/r/53.jpg"},
    { palavra: "Risco", descricao: "Perigo", url: "imagens/palavras/r/54.jpg"},
    { palavra: "Rodoviário", categoria: categorias.transportes.nome, url: "imagens/palavras/r/55.jpg"},
    { palavra: "Rolar", url: "imagens/palavras/r/56.jpg"},
    { palavra: "Rosa", categoria: categorias.cores.nome, url: "imagens/palavras/r/57.jpg"},
    { palavra: "Roubar", url: "imagens/palavras/r/58.jpg"},
    { palavra: "Roxo", categoria: categorias.cores.nome, url: "imagens/palavras/r/59.jpg"},
    { palavra: "Roxo", categoria: categorias.cores.nome, url: "imagens/palavras/r/60.jpg"},
    { palavra: "Rua", url: "imagens/palavras/r/61.jpg"},
    { palavra: "Ruim", url: "imagens/palavras/r/62.jpg"},
    { palavra: "Rural", url: "imagens/palavras/r/63.jpg"},
    
    { palavra: "Saber", url: "imagens/palavras/s/2.jpg"},
    { palavra: "Saber-não", url: "imagens/palavras/s/3.jpg"},
    { palavra: "Safado", url: "imagens/palavras/s/4.jpg"},
    { palavra: "Sala", url: "imagens/palavras/s/5.jpg"},
    { palavra: "Salário", url: "imagens/palavras/s/6.jpg"},
    { palavra: "Saldo", url: "imagens/palavras/s/7.jpg"},
    { palavra: "Salvar", url: "imagens/palavras/s/8.jpg"},
    { palavra: "Sangue", url: "imagens/palavras/s/9.jpg"},
    { palavra: "Sapato", url: "imagens/palavras/s/10.jpg"},
    { palavra: "Sapo", categoria: categorias.animais.nome, url: "imagens/palavras/s/11.jpg"},
    { palavra: "Satisfeit@", url: "imagens/palavras/s/12.jpg"},
    { palavra: "Saudade", url: "imagens/palavras/s/13.jpg"},
    { palavra: "Saúde", url: "imagens/palavras/s/14.jpg"},
    { palavra: "Secretari@", categoria: categorias.profissoes.nome, url: "imagens/palavras/s/15.jpg"},
    { palavra: "Século", url: "imagens/palavras/s/16.jpg"},
    { palavra: "Sede", url: "imagens/palavras/s/17.jpg"},
    { palavra: "Segredo", url: "imagens/palavras/s/18.jpg"},
    { palavra: "Seguir", url: "imagens/palavras/s/19.jpg"},
    { palavra: "Segurança", url: "imagens/palavras/s/21.jpg"},
    { palavra: "Segurar", url: "imagens/palavras/s/22.jpg"},
    { palavra: "Semana", url: "imagens/palavras/s/23.jpg"},
    { palavra: "Semestre", url: "imagens/palavras/s/24.jpg"},
    { palavra: "Seminário", url: "imagens/palavras/s/25.jpg"},
    { palavra: "Sempre", url: "imagens/palavras/s/26.jpg"},
    { palavra: "Senador", categoria: categorias.profissoes.nome, url: "imagens/palavras/s/27.jpg"},
    { palavra: "Senhor", url: "imagens/palavras/s/28.jpg"},
    { palavra: "Sensível", url: "imagens/palavras/s/29.jpg"},
    { palavra: "Sentar", url: "imagens/palavras/s/30.jpg"},
    { palavra: "Sentir", url: "imagens/palavras/s/31.jpg"},
    { palavra: "Separar", url: "imagens/palavras/s/32.jpg"},
    { palavra: "Seqüestro", url: "imagens/palavras/s/33.jpg"},
    { palavra: "Séri@", url: "imagens/palavras/s/34.jpg"},
    { palavra: "Série", url: "imagens/palavras/s/35.jpg"},
    { palavra: "Serviço", url: "imagens/palavras/s/36.jpg"},
    { palavra: "Serviço Social", categoria: categorias.profissoes.nome, url: "imagens/palavras/s/37.jpg"},
    { palavra: "Setor", url: "imagens/palavras/s/39.jpg"},
    { palavra: "Sexo", url: "imagens/palavras/s/40.jpg"},
    { palavra: "Shopping", url: "imagens/palavras/s/42.jpg"},
    { palavra: "Significado", url: "imagens/palavras/s/43.jpg"},
    { palavra: "Silêncio", url: "imagens/palavras/s/44.jpg"},
    { palavra: "Sim", url: "imagens/palavras/s/45.jpg"},
    { palavra: "Símbolo", url: "imagens/palavras/s/46.jpg"},
    { palavra: "Simpátic@", url: "imagens/palavras/s/47.jpg"},
    { palavra: "Simples", url: "imagens/palavras/s/48.jpg"},
    { palavra: "Sinal", url: "imagens/palavras/s/49.jpg"},
    { palavra: "Sincer@", url: "imagens/palavras/s/50.jpg"},
    { palavra: "Sindicato", url: "imagens/palavras/s/51.jpg"},
    { palavra: "Siri", categoria: categorias.animais.nome, url: "imagens/palavras/s/52.jpg"},
    { palavra: "Sobrar", url: "imagens/palavras/s/53.jpg"},
    { palavra: "Sobrenome", url: "imagens/palavras/s/54.jpg"},
    { palavra: "Sobrinh@", url: "imagens/palavras/s/55.jpg"},
    { palavra: "Sociedade / Social", url: "imagens/palavras/s/56.jpg"},
    { palavra: "Sócio", categoria: categorias.profissoes.nome, url: "imagens/palavras/s/57.jpg"},
    { palavra: "Sofrer", url: "imagens/palavras/s/58.jpg"},
    { palavra: "Sogr@", url: "imagens/palavras/s/59.jpg"},
    { palavra: "Solicitar", url: "imagens/palavras/s/60.jpg"},
    { palavra: "Soltar", url: "imagens/palavras/s/61.jpg"},
    { palavra: "Solteir@", url: "imagens/palavras/s/62.jpg"},
    { palavra: "Som", url: "imagens/palavras/s/63.jpg"},
    { palavra: "Somar", url: "imagens/palavras/s/64.jpg"},
    { palavra: "Somente / Só", url: "imagens/palavras/s/65.jpg"},
    { palavra: "Sonhar", url: "imagens/palavras/s/66.jpg"},
    { palavra: "Sono", url: "imagens/palavras/s/67.jpg"},
    { palavra: "Sorte", url: "imagens/palavras/s/68.jpg"},
    { palavra: "Sozinh@ / Solidão", url: "imagens/palavras/s/69.jpg"},
    { palavra: "Suave", url: "imagens/palavras/s/70.jpg"},
    { palavra: "Substituir", url: "imagens/palavras/s/71.jpg"},
    { palavra: "Sugestão", url: "imagens/palavras/s/72.jpg"},
    { palavra: "Suj@", url: "imagens/palavras/s/73.jpg"},
    { palavra: "Sul", categoria: categorias.pontosCardeais.nome, url: "imagens/palavras/s/74.jpg"},
    { palavra: "Sumir", url: "imagens/palavras/s/75.jpg"},
    { palavra: "Superior", url: "imagens/palavras/s/76.jpg"},
    { palavra: "Supermercado", url: "imagens/palavras/s/77.jpg"},
    { palavra: "Supervisor@", categoria: categorias.profissoes.nome, url: "imagens/palavras/s/78.jpg"},
    { palavra: "Supletivo", url: "imagens/palavras/s/79.jpg"},
    { palavra: "Surd@", url: "imagens/palavras/s/80.jpg"},
    { palavra: "Surpresa", url: "imagens/palavras/s/81.jpg"},
    { palavra: "Suspender", descricao: "Ex.: Ele comportou-se mal na escola e foi suspenso", url: "imagens/palavras/s/82.jpg"},
    { palavra: "Susto", url: "imagens/palavras/s/83.jpg"},    
    
    { palavra: "Talvez", url: "imagens/palavras/t/1.jpg"},
    { palavra: "Tamanduá", categoria: categorias.animais.nome, url: "imagens/palavras/t/2.jpg"},
    { palavra: "Também", url: "imagens/palavras/t/3.jpg"},
    { palavra: "Tarde", url: "imagens/palavras/t/4.jpg"},
    { palavra: "Tartaruga", categoria: categorias.animais.nome, url: "imagens/palavras/t/5.jpg"},
    { palavra: "Tatu", categoria: categorias.animais.nome, url: "imagens/palavras/t/6.jpg"},
    { palavra: "Taxí", categoria: categorias.transportes.nome, url: "imagens/palavras/t/7.jpg"},
    { palavra: "Teatro", url: "imagens/palavras/t/8.jpg"},
    { palavra: "Técnico / Treinador", categoria: categorias.profissoes.nome, url: "imagens/palavras/t/9.jpg"},
    { palavra: "Tecnologia", url: "imagens/palavras/t/10.jpg"},
    { palavra: "Telefone", url: "imagens/palavras/t/11.jpg"},
    { palavra: "Telegrama", url: "imagens/palavras/t/12.jpg"},
    { palavra: "Televisão", url: "imagens/palavras/t/13.jpg"},
    { palavra: "Tema", descricao: "Trabalho escolar", url: "imagens/palavras/t/14.jpg"},
    { palavra: "Temperatura", url: "imagens/palavras/t/15.jpg"},
    { palavra: "Tempo", descricao: "Pedir tempo em jogos esportivos e namoros", url: "imagens/palavras/t/16.jpg"},
    { palavra: "Tempo", descricao: "Condições climáticas", url: "imagens/palavras/t/17.jpg"},
    { palavra: "Temporário", url: "imagens/palavras/t/18.jpg"},
    { palavra: "Tênis", categoria: categorias.esportes.nome, url: "imagens/palavras/t/19.jpg"},
    { palavra: "Tentar", url: "imagens/palavras/t/20.jpg"},
    { palavra: "Ter", url: "imagens/palavras/t/21.jpg"},
    { palavra: "Ter-não", url: "imagens/palavras/t/22.jpg"},
    { palavra: "Terapia Ocupacional", categoria: categorias.profissoes.nome, url: "imagens/palavras/t/23.jpg"},
    { palavra: "Terra", descricao: "Natureza", url: "imagens/palavras/t/25.jpg"},
    { palavra: "Terra", descricao: "Planeta", url: "imagens/palavras/t/26.jpg"},
    { palavra: "Tesoura", url: "imagens/palavras/t/27.jpg"},
    { palavra: "Tesoureir@", url: "imagens/palavras/t/28.jpg"},
    { palavra: "Teste", url: "imagens/palavras/t/29.jpg"},
    { palavra: "Testemunha", descricao: "Pessoa que viu ou ouviu algo, ou que é chamada a d epor  sobre o que viu ou ouviu", url: "imagens/palavras/t/30.jpg"},
    { palavra: "Testemunha", descricao: "", url: "imagens/palavras/t/31.jpg"},
    { palavra: "Texto", url: "imagens/palavras/t/32.jpg"},
    { palavra: "Tigre", categoria: categorias.animais.nome, url: "imagens/palavras/t/33.jpg"},
    { palavra: "Tipo", url: "imagens/palavras/t/34.jpg"},
    { palavra: "Tirar", url: "imagens/palavras/t/35.jpg"},
    { palavra: "Tiro (bala)", url: "imagens/palavras/t/36.jpg"},
    { palavra: "Ti@", categoria: categorias.familia.nome, url: "imagens/palavras/t/37.jpg"},
    { palavra: "Todos os dias", url: "imagens/palavras/t/38.jpg"},
    { palavra: "Tontear", url: "imagens/palavras/t/39.jpg"},
    { palavra: "Titulo de eleitor", url: "imagens/palavras/t/40.jpg"},
    { palavra: "Todos / Tudo", url: "imagens/palavras/t/41.jpg"},
    { palavra: "Torcer", url: "imagens/palavras/t/42.jpg"},
    { palavra: "Torneio", url: "imagens/palavras/t/43.jpg"},
    { palavra: "Tosse", url: "imagens/palavras/t/44.jpg"},
    { palavra: "Trabalhar", url: "imagens/palavras/t/45.jpg"},
    { palavra: "Tradicional", url: "imagens/palavras/t/46.jpg"},
    { palavra: "Tradução", url: "imagens/palavras/t/47.jpg"},
    { palavra: "Trair", url: "imagens/palavras/t/48.jpg"},
    { palavra: "Tranqüilo", url: "imagens/palavras/t/49.jpg"},
    { palavra: "Transferência", url: "imagens/palavras/t/50.jpg"},
    { palavra: "Tratar", descricao: "Atendimento", url: "imagens/palavras/t/51.jpg"},
    { palavra: "Tratar", descricao: "Tratamento saúde", url: "imagens/palavras/t/52.jpg"},
    { palavra: "Trauma", url: "imagens/palavras/t/53.jpg"},
    { palavra: "Trazer", url: "imagens/palavras/t/54.jpg"},
    { palavra: "Treinar", url: "imagens/palavras/t/55.jpg"},
    { palavra: "Tribunal", url: "imagens/palavras/t/56.jpg"},
    { palavra: "Trocar", descricao: "Mudar, Alterar", url: "imagens/palavras/t/57.jpg"},
    { palavra: "Trocar", descricao: "Substituir", url: "imagens/palavras/t/58.jpg"},
    { palavra: "Tumor", url: "imagens/palavras/t/59.jpg"},
    { palavra: "Tubarão", categoria: categorias.animais.nome, url: "imagens/palavras/t/60.jpg"},
    { palavra: "Turma", url: "imagens/palavras/t/61.jpg"},
    { palavra: "Triste", url: "imagens/palavras/t/62.jpg"},
    { palavra: "Troco", url: "imagens/palavras/t/63.jpg"},
        
    { palavra: "Últim@", descricao: "Que está ou vem no final (Ex: Meu apartamento é no último andar)", url: "imagens/palavras/u/1.jpg"},
    { palavra: "Últim@", descricao: "Final, Derradeiro (a), Que sobra. (Ex: Fui a última pessoa a vê-lo antes do acidente)", url: "imagens/palavras/u/2.jpg"},
    { palavra: "Unha", url: "imagens/palavras/u/3.jpg"},
    { palavra: "Únic@", url: "imagens/palavras/u/4.jpg"},
    { palavra: "Uniforme", url: "imagens/palavras/u/5.jpg"},
    { palavra: "Unir", url: "imagens/palavras/u/6.jpg"},
    { palavra: "Universal", url: "imagens/palavras/u/7.jpg"},
    { palavra: "Universidade", url: "imagens/palavras/u/8.jpg"},
    { palavra: "Urgente", url: "imagens/palavras/u/9.jpg"},
    { palavra: "Urina", url: "imagens/palavras/u/10.jpg"},
    { palavra: "Urso", categoria: categorias.animais.nome, url: "imagens/palavras/u/11.jpg"},
    { palavra: "Urso panda", categoria: categorias.animais.nome, url: "imagens/palavras/u/12.jpg"},
    { palavra: "Urso polar", categoria: categorias.animais.nome, url: "imagens/palavras/u/13.jpg"},
    { palavra: "Usar", url: "imagens/palavras/u/14.jpg"},
    { palavra: "Uva", categoria: categorias.frutas.nome, url: "imagens/palavras/u/15.jpg"},

    { palavra: "Vaca", categoria: categorias.animais.nome, url: "imagens/palavras/v/1.jpg"},
    { palavra: "Vacina", url: "imagens/palavras/v/2.jpg"},
    { palavra: "Vaga", descricao: "Lugar vago em emprego", url: "imagens/palavras/v/3.jpg"},
    { palavra: "Vaga", descricao: "Palavra", url: "imagens/palavras/v/4.jpg"},
    { palavra: "Vagabund@", url: "imagens/palavras/v/5.jpg"},
    { palavra: "Vaidos@", url: "imagens/palavras/v/6.jpg"},
    { palavra: "Vale a pena", url: "imagens/palavras/v/7.jpg"},
    { palavra: "Validade", url: "imagens/palavras/v/8.jpg"},
    { palavra: "Valor", url: "imagens/palavras/v/9.jpg"},
    { palavra: "Vamos", url: "imagens/palavras/v/10.jpg"},
    { palavra: "Vapor", url: "imagens/palavras/v/11.jpg"},
    { palavra: "Vári@", url: "imagens/palavras/v/12.jpg"},
    { palavra: "Vazi@", url: "imagens/palavras/v/13.jpg"},
    { palavra: "Vela", url: "imagens/palavras/v/14.jpg"},
    { palavra: "Velh@", url: "imagens/palavras/v/15.jpg"},
    { palavra: "Vencer", url: "imagens/palavras/v/16.jpg"},
    { palavra: "Vender", url: "imagens/palavras/v/17.jpg"},
    { palavra: "Veneno", url: "imagens/palavras/v/18.jpg"},
    { palavra: "Vento", url: "imagens/palavras/v/19.jpg"},
    { palavra: "Ver", url: "imagens/palavras/v/20.jpg"},
    { palavra: "Verbo", url: "imagens/palavras/v/21.jpg"},
    { palavra: "Verdade", url: "imagens/palavras/v/22.jpg"},
    { palavra: "Verde", categoria: categorias.cores.nome, url: "imagens/palavras/v/23.jpg"},
    { palavra: "Vereador@", categoria: categorias.profissoes.nome, url: "imagens/palavras/v/24.jpg"},
    { palavra: "Vermelho", categoria: categorias.cores.nome, url: "imagens/palavras/v/25.jpg"},
    { palavra: "Vestibular", url: "imagens/palavras/v/26.jpg"},
    { palavra: "Veterinário", categoria: categorias.profissoes.nome, url: "imagens/palavras/v/27.jpg"},
    { palavra: "Viajar", url: "imagens/palavras/v/28.jpg"},
    { palavra: "Vibrar", url: "imagens/palavras/v/29.jpg"},
    { palavra: "Vice", url: "imagens/palavras/v/30.jpg"},
    { palavra: "Viciar", url: "imagens/palavras/v/31.jpg"},
    { palavra: "Vida", url: "imagens/palavras/v/32.jpg"},
    { palavra: "Vidro", url: "imagens/palavras/v/33.jpg"},
    { palavra: "Vingar", url: "imagens/palavras/v/34.jpg"},
    { palavra: "Vinho", url: "imagens/palavras/v/35.jpg"},
    { palavra: "Violentar", url: "imagens/palavras/v/36.jpg"},
    { palavra: "Vir", url: "imagens/palavras/v/37.jpg"},
    { palavra: "Virgem", url: "imagens/palavras/v/38.jpg"},
    { palavra: "Vírus", url: "imagens/palavras/v/39.jpg"},
    { palavra: "Visitar", url: "imagens/palavras/v/40.jpg"},
    { palavra: "Viver", url: "imagens/palavras/v/41.jpg"},
    { palavra: "Vizinho", url: "imagens/palavras/v/42.jpg"},
    { palavra: "Vocabuário", descricao: "", url: "imagens/palavras/v/43.jpg"},
    { palavra: "Vocabulário", descricao: "", url: "imagens/palavras/v/44.jpg"},
    { palavra: "Você", url: "imagens/palavras/v/45.jpg"},
    { palavra: "Você-dois", url: "imagens/palavras/v/46.jpg"},
    { palavra: "Voltar", url: "imagens/palavras/v/47.jpg"},
    { palavra: "Vomitar", url: "imagens/palavras/v/48.jpg"},
    { palavra: "Vontade", url: "imagens/palavras/v/49.jpg"},
    { palavra: "Votar", url: "imagens/palavras/v/50.jpg"},
    { palavra: "Vovô", categoria: categorias.familia.nome, url: "imagens/palavras/v/51.jpg"},
    { palavra: "Vovó", categoria: categorias.familia.nome, url: "imagens/palavras/v/52.jpg"},
    { palavra: "Voz", url: "imagens/palavras/v/53.jpg"},
    { palavra: "Vulcão", url: "imagens/palavras/v/54.jpg"},
    
    { palavra: "Xingar", url: "imagens/palavras/x/1.jpg"},
    { palavra: "Xinga-me", url: "imagens/palavras/x/2.jpg"},
    { palavra: "Xerox", url: "imagens/palavras/x/3.jpg"},
    { palavra: "Xale", url: "imagens/palavras/x/4.jpg"},
    { palavra: "Xícara", url: "imagens/palavras/x/5.jpg"},
    { palavra: "Xarope", url: "imagens/palavras/x/6.jpg"},
    
    { palavra: "Zebra", categoria: categorias.animais.nome, url: "imagens/palavras/z/1.jpg"},
    { palavra: "Zelador", categoria: categorias.profissoes.nome, url: "imagens/palavras/z/2.jpg"},
    { palavra: "Zôo", url: "imagens/palavras/z/3.jpg"},
    { palavra: "Zíper", url: "imagens/palavras/z/4.jpg"},

    { palavra: "Zero",      categoria: categorias.numeros.nome, url: "imagens/numeros/0.jpg"},
    { palavra: "Um",        categoria: categorias.numeros.nome, url: "imagens/numeros/1.jpg"},
    { palavra: "Dois",      categoria: categorias.numeros.nome, url: "imagens/numeros/2.jpg"},
    { palavra: "Três",      categoria: categorias.numeros.nome, url: "imagens/numeros/3.jpg"},
    { palavra: "Quatro",    categoria: categorias.numeros.nome, url: "imagens/numeros/4.jpg"},
    { palavra: "Cinco",     categoria: categorias.numeros.nome, url: "imagens/numeros/5.jpg"},
    { palavra: "Seis",      categoria: categorias.numeros.nome, url: "imagens/numeros/6.jpg"},
    { palavra: "Sete",      categoria: categorias.numeros.nome, url: "imagens/numeros/7.jpg"},
    { palavra: "Oito",      categoria: categorias.numeros.nome, url: "imagens/numeros/8.jpg"},
    { palavra: "Nove",      categoria: categorias.numeros.nome, url: "imagens/numeros/9.jpg"},
    { palavra: "Dez",       categoria: categorias.numeros.nome, url: "imagens/numeros/10.jpg"},
    { palavra: "Onze",      categoria: categorias.numeros.nome, url: "imagens/numeros/11.jpg"},
    { palavra: "Mil",       categoria: categorias.numeros.nome, url: "imagens/numeros/12.jpg"},
    { palavra: "Dez mil",   categoria: categorias.numeros.nome, url: "imagens/numeros/13.jpg"},    

    { palavra: "Segunda-feira", categoria: categorias.diasSemana.nome, url: "imagens/palavras/s/20.jpg"},
    { palavra: "Terça-feira",   categoria: categorias.diasSemana.nome, url: "imagens/palavras/t/24.jpg"},
    { palavra: "Quarta-feira",  categoria: categorias.diasSemana.nome, url: "imagens/palavras/q/10.jpg"},
    { palavra: "Quinta-feira",  categoria: categorias.diasSemana.nome, url: "imagens/palavras/q/25.jpg"},
    { palavra: "Sexta-feira",   categoria: categorias.diasSemana.nome, url: "imagens/palavras/s/41.jpg"},    
    { palavra: "Sábado",        categoria: categorias.diasSemana.nome, url: "imagens/palavras/s/1.jpg"},
    { palavra: "Domingo",       categoria: categorias.diasSemana.nome, url: "imagens/palavras/d/53.jpg"},    

    { palavra: "Janeiro",   categoria: categorias.meses.nome, url: "imagens/palavras/j/2.jpg"},
    { palavra: "Fevereiro", categoria: categorias.meses.nome, url: "imagens/palavras/f/26.jpg"}, 
    { palavra: "Março",     categoria: categorias.meses.nome, url: "imagens/palavras/m/29.jpg"},
    { palavra: "Abril",     categoria: categorias.meses.nome, url: "imagens/palavras/a/3.jpg"},
    { palavra: "Maio",      categoria: categorias.meses.nome, url: "imagens/palavras/m/12.jpg"},
    { palavra: "Junho",     categoria: categorias.meses.nome, url: "imagens/palavras/j/8.jpg"},
    { palavra: "Julho",     categoria: categorias.meses.nome, url: "imagens/palavras/j/9.jpg"},
    { palavra: "Agosto ",   categoria: categorias.meses.nome, url: "imagens/palavras/a/26.jpg"},
    { palavra: "Setembro",  categoria: categorias.meses.nome, url: "imagens/palavras/s/38.jpg"},
    { palavra: "Outubro",   categoria: categorias.meses.nome, url: "imagens/palavras/o/35.jpg"},
    { palavra: "Novembro",  categoria: categorias.meses.nome, url: "imagens/palavras/n/32.jpg"},
    { palavra: "Dezembro",  categoria: categorias.meses.nome, url: "imagens/palavras/d/30.jpg"},    
];
